/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages -- Responsive media and native links in an isolated server renderer. */
import type { NicheBlock, NicheMedia, NichePackage, NichePage } from '@/lib/niche-sites';
import { nichePagePath } from '@/lib/niche-sites';
import { nicheJsonLd } from '@/lib/niche-seo';
import { nicheBreadcrumbs } from '@/lib/niche-schema-core.mjs';
import { nicheNetworkContact } from '@/lib/niche-network';
import { imageSrcSet, visibleImageCredit } from '@/lib/niche-media.mjs';
import { ArticleMeta } from './article-meta';
import { InterestTracking } from './interest-tracking';
import { LinkedText } from './linked-text';
import s from './akmenas-site.module.css';
type Props={pkg:NichePackage;page:NichePage;livePages:NichePage[]};
type Group={title:string;blocks:NicheBlock[]};
function groupBody(body:NicheBlock[]){const groups:Group[]=[];for(const b of body){if(b.type==='heading'&&b.level===2)groups.push({title:b.text,blocks:[]});else if(groups.length)groups.at(-1)!.blocks.push(b);}return groups;}
function Arrow(){return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;}
function Photo({page,asset=page.media[0],eager=false,sizes='(max-width: 760px) calc(100vw - 40px), 720px'}:{page:NichePage;asset?:NicheMedia;eager?:boolean;sizes?:string}){if(!asset)return null;return <><img src={asset.src} srcSet={imageSrcSet(page.media,asset)} sizes={sizes} width={asset.width} height={asset.height} alt={asset.alt} loading={eager?'eager':'lazy'} fetchPriority={eager?'high':undefined} decoding="async"/>{visibleImageCredit(asset)&&<span className={s.credit}>{visibleImageCredit(asset)}</span>}</>;}
function Body({body,page,livePages}:Pick<Props,'page'|'livePages'>&{body:NicheBlock[]}){return body.map((b,i)=>b.type==='paragraph'?<p key={i}><LinkedText text={b.text} page={page} livePages={livePages}/></p>:b.type==='heading'?b.level===2?<h2 key={i} id={'skyrius-'+page.body.indexOf(b)}>{b.text}</h2>:<h3 key={i}>{b.text}</h3>:b.type==='list'?<ul key={i}>{b.items.map(v=><li key={v}><LinkedText text={v} page={page} livePages={livePages}/></li>)}</ul>:<figure key={i}><Photo page={page} asset={page.media.find(v=>v.id===b.assetId)}/></figure>);}
function Brand(){return <a className={s.brand} href="/" aria-label="akmenas.lt – pradžia">akmenas<span>.lt</span></a>;}
function Header({livePages,page}:Pick<Props,'livePages'|'page'>){const has=(slug:string)=>livePages.some(v=>v.slug===slug);return <><a className={s.skip} href="#turinys">Pereiti prie turinio</a><header className={s.header}><Brand/><nav className={s.nav} aria-label="Pagrindinė navigacija">{has('gidas/stalvirsiu-medziagu-palyginimas')&&<a href="/gidas/stalvirsiu-medziagu-palyginimas">Medžiagos</a>}{has('gidai')&&<a href="/gidai">Gidai</a>}{has('apie-projekta')&&<a href="/apie-projekta">Apie projektą</a>}</nav>{has('kontaktai')&&<a className={s.headerAction} href={page.slug==='kontaktai'?'#uzklausa':'/kontaktai#uzklausa'}>Aprašyti poreikį <Arrow/></a>}<details className={s.menu}><summary>Meniu <svg width="18" height="18" viewBox="0 0 18 18" aria-hidden="true"><path d="M2 5h14M2 12h14" stroke="currentColor" strokeWidth="1.5"/></svg></summary><nav aria-label="Mobilioji navigacija"><a href="/">Pradžia</a>{has('gidai')&&<a href="/gidai">Visi gidai</a>}{has('gidas/stalvirsiu-medziagu-palyginimas')&&<a href="/gidas/stalvirsiu-medziagu-palyginimas">Medžiagos</a>}{has('apie-projekta')&&<a href="/apie-projekta">Apie projektą</a>}{has('kontaktai')&&<a href="/kontaktai#uzklausa">Aprašyti poreikį</a>}</nav></details></header></>;}
function Footer({pkg,livePages}:Pick<Props,'pkg'|'livePages'>){const contact=nicheNetworkContact(pkg.siteId);return <footer className={s.footer}><div className={s.footerTop}><div><Brand/><p>{pkg.site.offer}</p></div><div><h2>Pasirinkimui</h2>{livePages.filter(v=>['gidai','stalvirsio-poreikis','kontaktai'].includes(v.slug)).map(v=><a key={v.id} href={nichePagePath(v)}>{v.slug==='gidai'?'Visi gidai':v.slug==='kontaktai'?'Kontaktai':'Poreikio paaiškinimas'}</a>)}</div><div><h2>{contact.operatorName}</h2><a href={'mailto:'+contact.email}>{contact.email}</a>{livePages.filter(v=>['apie-projekta','redakcija','privatumas','naudojimo-salygos'].includes(v.slug)).map(v=><a key={v.id} href={nichePagePath(v)}>{v.slug==='redakcija'?'Redakcija ir metodika':v.slug==='privatumas'?'Privatumas':v.slug==='apie-projekta'?'Apie projektą':'Naudojimo sąlygos'}</a>)}</div></div><div className={s.footerBottom}><span>Informacinis projektas · {pkg.canonicalHost}</span><span>Mūsų verslas automatizuotas su verslomatika.lt</span></div></footer>;}
function GuideList({pages,compact=false}:{pages:NichePage[];compact?:boolean}){return <div className={compact?s.guideTiles:s.guideRows}>{pages.map(page=><article key={page.id}><a className={s.guideImage} href={nichePagePath(page)} tabIndex={-1} aria-hidden="true"><Photo page={page} sizes={compact?'(max-width: 760px) calc(100vw - 40px), 390px':'(max-width: 760px) calc(100vw - 40px), 360px'}/></a><div><h3><a href={nichePagePath(page)}>{page.title}</a></h3><p>{page.description}</p><a className={s.textLink} href={nichePagePath(page)}>Skaityti gidą <Arrow/></a></div></article>)}</div>;}
function InquiryLink({title,body,livePages,page}:{title:string;body:NicheBlock[]}&Pick<Props,'page'|'livePages'>){return <section className={s.inquiryBand}><h2>{title}</h2><div><Body body={body} page={page} livePages={livePages}/>{livePages.some(v=>v.slug==='kontaktai')&&<a className={s.button} href="/kontaktai#uzklausa">Aprašyti poreikį <Arrow/></a>}</div></section>;}
function Home(props:Props){const {page,livePages}=props,g=groupBody(page.body),guides=livePages.filter(v=>v.type==='guide');const first=g[0],materials=g[1],questions=g[2],prepare=g[3],last=g[4];const hero=page.media[0],comparison=page.media.find(v=>v.alt!==hero?.alt),planning=livePages.find(v=>v.slug==='gidas/pasiruosimas-stalvirsio-uzklausai');const segments=first.title.split('. ');return <main id="turinys" tabIndex={-1}><section className={s.hero}><div className={s.heroTop}><h1>{segments.map((v,i)=><span key={v}>{v}{i===0&&segments.length>1?'. ':''}</span>)}</h1><div className={s.heroIntro}><Body body={first.blocks} page={page} livePages={livePages}/><div className={s.actions}>{livePages.some(v=>v.slug==='gidas/stalvirsiu-medziagu-palyginimas')&&<a className={s.button} href="/gidas/stalvirsiu-medziagu-palyginimas">Palyginti medžiagas <Arrow/></a>}{livePages.some(v=>v.slug==='kontaktai')&&<a className={s.textLink} href="/kontaktai#uzklausa">Aprašyti poreikį <Arrow/></a>}</div></div></div><figure className={s.heroPhoto}><Photo page={page} asset={hero} eager sizes="(max-width: 760px) calc(100vw - 40px), (max-width: 1440px) calc(100vw - 112px), 1328px"/></figure></section><section className={s.materialSection} id="medziagos"><div className={s.materialVisual}><Photo page={page} asset={comparison} sizes="(max-width: 760px) calc(100vw - 40px), 590px"/><p>Paviršių faktūrų iliustracija. Konkretų gaminį vertinkite pagal jo dokumentą ir tikrą pavyzdį.</p></div><div><h2>{materials.title}</h2><Body body={materials.blocks.filter(b=>b.type!=='list')} page={page} livePages={livePages}/><dl className={s.materialRows}>{materials.blocks.flatMap(b=>b.type==='list'?b.items:[]).map(v=>{const pos=v.indexOf(':');return <div key={v}><dt>{v.slice(0,pos)}</dt><dd>{v.slice(pos+1)}</dd></div>;})}</dl></div></section><section className={s.guideSection}><div className={s.sectionHead}><h2>{questions.title}</h2><Body body={questions.blocks} page={page} livePages={livePages}/></div><GuideList pages={guides} compact/></section><section className={s.prepareSection}><div><h2>{prepare.title}</h2><Body body={prepare.blocks} page={page} livePages={livePages}/>{planning&&<a className={s.textLink} href={nichePagePath(planning)}>Peržiūrėti pasiruošimo sąrašą <Arrow/></a>}</div><figure>{planning&&<Photo page={planning} sizes="(max-width: 760px) calc(100vw - 40px), 590px"/>}</figure></section><InquiryLink title={last.title} body={last.blocks} {...props}/></main>;}
function Breadcrumb({pkg,page,livePages}:Props){const items=nicheBreadcrumbs(pkg,page,livePages) as {name:string;path:string}[];return <nav className={s.breadcrumb} aria-label="Puslapio kelias"><ol>{items.map((item,i)=><li key={item.path}>{i<items.length-1?<a href={item.path}>{item.name}</a>:<span aria-current="page">{item.name}</span>}</li>)}</ol></nav>;}
function Sources({page}:Pick<Props,'page'>){return page.externalLinks?.length?<section className={s.sources}><h2>Šaltiniai ir jų paskirtis</h2><ul>{page.externalLinks.map(v=><li key={v.url}><a href={v.url}>{v.label}</a><p>{v.reason}</p></li>)}</ul></section>:null;}
function Form({pkg}:Pick<Props,'pkg'>){return <section id="uzklausa" className={s.formSection}><div><h2>Aprašykite savo poreikį</h2><p>Vietinėje peržiūroje naudokite testinius duomenis. Tikras el. laiškas šiame režime nesiunčiamas.</p><p>Žinutės gairės: situacija, forma, preliminarūs matmenys, įrangos modeliai ir konkretus klausimas. Nežinomus duomenis taip ir pažymėkite.</p><a className={s.textLink} href={'mailto:'+pkg.site.contact.email}>{pkg.site.contact.email} <Arrow/></a></div><form action="/uzklausa" method="post"><label htmlFor="vardas">Vardas <span>(privaloma)</span></label><input id="vardas" name="name" autoComplete="given-name" required minLength={2} maxLength={100}/><label htmlFor="pastas">El. paštas <span>(privaloma)</span></label><input id="pastas" name="email" type="email" autoComplete="email" required maxLength={250}/><label htmlFor="zinute">Jūsų situacija ir klausimas <span>(privaloma)</span></label><p className={s.fieldHelp} id="zinutes-gaires">Bent 20 ženklų. Neįrašykite tikslaus adreso, mokėjimo duomenų ar slaptažodžių.</p><textarea id="zinute" name="message" required minLength={20} maxLength={3000} rows={7} aria-describedby="zinutes-gaires"/><div className={s.trap} aria-hidden="true"><label htmlFor="website">Svetainė</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><label className={s.consent}><input type="checkbox" name="consent" value="yes" required/> <span>Sutinku, kad pateikti duomenys būtų naudojami šiai užklausai apdoroti. Perskaičiau <a href="/privatumas">privatumo informaciją</a>.</span></label><p className={s.fieldHelp}>Užklausa nėra užsakymas ar rinkodaros prenumerata. Sėkmės pranešimas rodomas tik išsaugojus įrašą.</p><button className={s.button} type="submit">Pateikti užklausą <Arrow/></button></form></section>;}
function Inner(props:Props){const {pkg,page,livePages}=props;const guides=livePages.filter(v=>v.type==='guide'),isGuide=page.type==='guide',headings=page.body.flatMap((b,i)=>b.type==='heading'&&b.level===2?[{text:b.text,id:'skyrius-'+i}]:[]);return <main id="turinys" tabIndex={-1} className={s.inner}><Breadcrumb {...props}/><div className={s.articleHeader}><h1>{page.title}</h1>{isGuide&&<ArticleMeta pkg={pkg} page={page} pages={livePages} className={s.meta}/>}</div>{page.slug==='gidai'?<><div className={s.indexIntro}><Body body={page.body} page={page} livePages={livePages}/></div><GuideList pages={guides}/></>:<><div className={s.readingLayout}>{isGuide&&<aside className={s.contents}><details open><summary>Šiame gide</summary><nav aria-label="Gido turinys">{headings.map(v=><a key={v.id} href={'#'+v.id}>{v.text}</a>)}</nav></details><a className={s.textLink} href="/gidai">Visi gidai <Arrow/></a></aside>}<article className={isGuide?s.article:s.simpleArticle}>{page.media.length>0&&<figure className={s.articlePhoto}><Photo page={page} eager sizes="(max-width: 760px) calc(100vw - 40px), 760px"/></figure>}<Body body={page.body} page={page} livePages={livePages}/><Sources page={page}/>{isGuide&&<section className={s.related}><h2>Kitas naudingas žingsnis</h2>{page.links.map(v=>{const target=livePages.find(p=>p.id===v.targetPageId);return target?<a key={v.targetPageId} href={nichePagePath(target)}>{target.title}<Arrow/></a>:null;})}</section>}</article></div>{page.slug==='kontaktai'&&<Form pkg={pkg}/>}</>}</main>;}
export function AkmenasSite(props:Props){return <div className={s.site}>{['fraunces-subset-0.woff2','fraunces-subset-1.woff2','manrope-latin-ext-3911b66d9f2e.woff2','manrope-latin-a30ddcd34970.woff2'].map(file=><link key={file} rel="preload" href={'/fonts/akmenas/'+file} as="font" type="font/woff2" crossOrigin="anonymous"/>)}<Header {...props}/>{props.page.type==='home'?<Home {...props}/>:<Inner {...props}/>}<Footer {...props}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(props.pkg,props.page)}}/><InterestTracking/></div>;}
