/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages, @next/next/no-css-tags -- Host-aware pages, shared WebP srcsets and this host's self-hosted font sheet. */
import type {NichePackage,NichePage,NicheBlock,NicheMedia} from '@/lib/niche-sites';
import {nichePagePath} from '@/lib/niche-sites';
import {nicheJsonLd} from '@/lib/niche-seo';
import {nicheBreadcrumbs} from '@/lib/niche-schema-core.mjs';
import {imageSrcSet} from '@/lib/niche-media.mjs';
import {ArticleMeta} from './article-meta';
import {InterestTracking} from './interest-tracking';
import {LinkedText} from './linked-text';
import {DiagnosticInquiry} from './autoelektrikaivilniuje-site.tools';
import styles from './autoelektrikaivilniuje-site.module.css';
type Props={pkg:NichePackage;page:NichePage;livePages:NichePage[]};

function Mark(){return <svg width="40" height="40" viewBox="0 0 40 40" aria-hidden="true" fill="none"><path d="M3 10h12v20H3M37 10H25v20h12M15 20h10" stroke="currentColor" strokeWidth="3"/><circle cx="20" cy="20" r="3" fill="currentColor"/></svg>}
function Picture({page,asset,priority=false,sizes}:{page:NichePage;asset?:NicheMedia;priority?:boolean;sizes:string}){return asset?<img src={asset.src} srcSet={imageSrcSet(page.media,asset)} sizes={sizes} width={asset.width} height={asset.height} alt={asset.alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async"/>:null}
function Blocks({blocks,page,livePages,offset=0}:{blocks:NicheBlock[];page:NichePage;livePages:NichePage[];offset?:number}){return blocks.map((b,i)=>b.type==='heading'?(b.level===2?<h2 key={i} id={`section-${i+offset}`}>{b.text}</h2>:<h3 key={i}>{b.text}</h3>):b.type==='paragraph'?<p key={i}><LinkedText text={b.text} page={page} livePages={livePages}/></p>:b.type==='list'?<ul key={i}>{b.items.map((t,j)=><li key={j}><LinkedText text={t} page={page} livePages={livePages}/></li>)}</ul>:<figure key={i}><Picture page={page} asset={page.media.find(a=>a.id===b.assetId)} sizes="(max-width: 800px) calc(100vw - 40px), 720px"/></figure>)}
function Header({page,livePages}:Props){const nav=<>{[['diagnostikos-poreikis','Poreikio tyrimas'],['gidai','Gidai']].map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`} aria-current={page.slug===slug?'page':undefined}>{label}</a>)}<a href="/kontaktai#poreikis" className={styles.navAction}>Aprašyti poreikį →</a></>;return <header className={styles.header}><div className={styles.headerInner}><a href="/" className={styles.brand} aria-label="Autoelektrikai Vilniuje – pradžia"><Mark/><span>Autoelektrikai{' '}<strong>Vilniuje</strong></span></a><nav className={styles.desktopNav} aria-label="Pagrindinė navigacija">{nav}</nav><details className={styles.mobileNav}><summary>Meniu</summary><nav aria-label="Mobilioji navigacija">{nav}</nav></details></div></header>}
function GuideList({livePages,page}:Props){const Heading=page.slug==='gidai'?'h2':'h3';return <div className={styles.guideList}>{livePages.filter(p=>p.type==='guide').map(p=><article key={p.id}><a href={nichePagePath(p)} className={styles.guidePhoto} tabIndex={-1} aria-hidden="true"><Picture page={p} asset={p.media[0]} sizes="(max-width: 760px) calc(100vw - 40px), (max-width: 1240px) 48vw, 580px"/></a><Heading><a href={nichePagePath(p)}>{p.title}</a></Heading><p>{p.description}</p><a href={nichePagePath(p)} className={styles.textLink}>Skaityti gidą →</a></article>)}</div>}
function Callout(){return <section className={styles.callout}><h2>Iš simptomo į aiškesnę žinutę.</h2><div><p>Aprašykite tikrą planinės diagnostikos poreikį Vilniuje. Išankstinis tyrimas, be serviso rezervacijos.</p><a className={styles.button} href="/kontaktai#poreikis">Paruošti poreikį →</a></div></section>}
function Home(props:Props){const {page,livePages}=props,images=page.media.filter((a,i,all)=>all.findIndex(x=>x.alt===a.alt)===i);const groups:{blocks:NicheBlock[];offset:number}[]=[];for(const [i,b]of page.body.entries()){if(b.type==='heading'&&b.level===2)groups.push({blocks:[b],offset:i});else if(groups.length)groups.at(-1)!.blocks.push(b)}return <>
 <section className={styles.hero}><div className={styles.heroInner}><h1>{page.title}</h1><div className={styles.heroDetail}><div><Blocks blocks={page.body.slice(0,1)} page={page} livePages={livePages}/><a className={styles.button} href="/kontaktai#poreikis">Aprašyti poreikį →</a><div className={styles.pilot}><Blocks blocks={page.body.slice(1,2)} page={page} livePages={livePages}/></div></div><figure><Picture page={page} asset={images[0]} sizes="(max-width: 800px) calc(100vw - 40px), (max-width: 1240px) calc((100vw - 104px) / 2), 568px" priority/><figcaption>Automobilio ir dirbtuvių konteksto iliustracija</figcaption></figure></div><nav className={styles.symptoms} aria-label="Simptomo gidai"><a href="/akumuliatorius-issikrauna"><span>Po stovėjimo</span>Akumuliatorius išsikrauna <b aria-hidden="true">↗</b></a><a href="/automobilis-neuzsiveda"><span>Bandant užvesti</span>Automobilis neužsiveda <b aria-hidden="true">↗</b></a></nav></div></section>
 <section className={styles.symptomSection}><div><Blocks blocks={groups[0]?.blocks.slice(0,2)??[]} offset={groups[0]?.offset} page={page} livePages={livePages}/><figure><Picture page={page} asset={images[1]} sizes="(max-width: 800px) calc(100vw - 40px), (max-width: 1240px) calc((100vw - 112px) * 5 / 11), 502px"/><figcaption>Pradėkite nuo to, ką pastebėjote</figcaption></figure></div><div className={styles.facts}><Blocks blocks={groups[0]?.blocks.slice(2)??[]} offset={(groups[0]?.offset??0)+2} page={page} livePages={livePages}/></div></section>
 <section className={styles.scope}><Blocks blocks={groups[1]?.blocks??[]} offset={groups[1]?.offset} page={page} livePages={livePages}/><a className={styles.textLink} href="/diagnostikos-kaina">Klausimai apie diagnostikos apimtį →</a></section>
 <section className={styles.guides}><div className={styles.sectionTitle}><h2>Aiškiau prieš diagnostiką</h2><a className={styles.textLink} href="/gidai">Visi gidai →</a></div><GuideList {...props}/></section>
 <section className={styles.prepare}><Blocks blocks={groups[2]?.blocks??[]} offset={groups[2]?.offset} page={page} livePages={livePages}/><a href="/diagnostikos-poreikis" className={styles.textLink}>Perskaityti pirmo etapo ribas →</a></section><Callout/>
 </>}
function Inner(props:Props){const {page,pkg,livePages}=props,isGuide=page.type==='guide',isIndex=page.slug==='gidai',toc=page.body.flatMap((b,i)=>b.type==='heading'&&b.level===2?[{text:b.text,id:`section-${i}`}]:[]);return <>
 <section className={styles.pageIntro}><nav className={styles.breadcrumb} aria-label="Puslapio kelias">{nicheBreadcrumbs(pkg,page,livePages).map((b:{name:string;path:string},i:number,arr:unknown[])=><span key={b.path}>{i>0&&' / '}{i===arr.length-1?<span aria-current="page">{b.name}</span>:<a href={b.path}>{b.name}</a>}</span>)}</nav><h1>{page.title}</h1><p>{page.description}</p>{page.slug==='kontaktai'&&<a href="#zinute" className={styles.textLink}>Rašyti žinutę →</a>}{isGuide&&<div className={styles.byline}><ArticleMeta pkg={pkg} page={page} pages={livePages}/><p>Vietinė peržiūra: publikavimo data suplanuota; ji nėra tikro domeno paskelbimo įrodymas.</p></div>}</section>
 {isIndex?<section className={styles.index}><GuideList {...props}/><div className={styles.indexCopy}><Blocks blocks={page.body} page={page} livePages={livePages}/></div></section>:<div className={`${styles.readingLayout} ${isGuide?styles.guideLayout:''}`}><article className={styles.article}>{isGuide&&<figure className={styles.articlePhoto}><Picture page={page} asset={page.media[0]} sizes="(max-width: 800px) calc(100vw - 40px), 720px" priority/><figcaption>Temos iliustracija</figcaption></figure>}<Blocks blocks={page.body} page={page} livePages={livePages}/>{!!page.externalLinks?.length&&<section id="saltiniai" className={styles.sources}><h2>Šaltiniai ir jų ribos</h2><ul>{page.externalLinks.map(s=><li key={s.url}><a href={s.url}>{s.label}</a><p>{s.reason}</p></li>)}</ul></section>}</article>{isGuide&&<aside className={styles.contents}><h2>Šiame gide</h2><details><summary>Gido turinys</summary><nav aria-label="Gido turinys">{toc.map(t=><a key={t.id} href={`#${t.id}`}>{t.text}</a>)}<a href="#saltiniai">Šaltiniai</a></nav></details><a href="/kontaktai#poreikis" className={styles.textLink}>Aprašyti savo poreikį →</a></aside>}</div>}
 {page.slug==='kontaktai'&&<DiagnosticInquiry/>}{page.links.length>0&&!isIndex&&<section className={styles.related}><h2>Tęskite savo klausimą</h2>{page.links.map(l=>{const target=livePages.find(p=>p.id===l.targetPageId);return target?<a key={target.id} href={nichePagePath(target)}>{l.label} →</a>:null})}</section>}{isGuide&&<Callout/>}
 </>}
function Footer({pkg,livePages}:Props){return <footer className={styles.footer}><div className={styles.footerTop}><div><a href="/" className={styles.brand}><Mark/><span>Autoelektrikai{' '}<strong>Vilniuje</strong></span></a><p>MB Pinet<br/><a href={`mailto:${pkg.site.contact.email}`}>{pkg.site.contact.email}</a></p></div><nav aria-label="Poraštės navigacija">{[['gidai','Gidai'],['kontaktai','Kontaktai'],['apie-projekta','Apie projektą'],['redakcija','Redakcija'],['privatumas','Privatumas'],['naudojimo-salygos','Naudojimo sąlygos']].map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`}>{label}</a>)}</nav></div><div className={styles.footerBottom}><p>{pkg.site.offer}</p><p>Mūsų verslas automatizuotas su <a href="https://verslomatika.lt/">verslomatika.lt</a></p></div></footer>}
export function AutoelektrikaivilniujeSite(props:Props){return <div className={styles.shell}><link rel="stylesheet" href="/fonts/autoelektrikaivilniuje/fonts.css"/><link rel="icon" href="/favicon.svg"/><InterestTracking/><a className={styles.skip} href="#turinys">Pereiti prie turinio</a><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(props.pkg,props.page)}}/><Header {...props}/><main id="turinys" tabIndex={-1}>{props.page.type==='home'?<Home {...props}/>:<Inner {...props}/>}</main><Footer {...props}/></div>}
