/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages, @next/next/no-css-tags -- Shared host-aware publication/media and self-hosted LT fonts. */
import type {NichePackage,NichePage,NicheBlock,NicheMedia} from '@/lib/niche-sites';
import {nichePagePath} from '@/lib/niche-sites';import {nicheJsonLd} from '@/lib/niche-seo';import {nicheBreadcrumbs} from '@/lib/niche-schema-core.mjs';import {imageSrcSet} from '@/lib/niche-media.mjs';
import {ArticleMeta} from './article-meta';import {InterestTracking} from './interest-tracking';import {LinkedText} from './linked-text';import {FacadeArea,RentalInquiry} from './fasadopastoliai-site.tools';import styles from './fasadopastoliai-site.module.css';
type Props={pkg:NichePackage;page:NichePage;livePages:NichePage[]};
function Mark(){return <svg width="38" height="38" viewBox="0 0 38 38" fill="none" aria-hidden="true"><path d="M6 33V5h26v28M6 14h26M6 24h26M19 5v28M6 5l13 9 13-9M6 24l13 9 13-9" stroke="currentColor" strokeWidth="2.4"/></svg>}
function Picture({page,asset,priority=false,sizes}:{page:NichePage;asset?:NicheMedia;priority?:boolean;sizes:string}){return asset?<img src={asset.src} srcSet={imageSrcSet(page.media,asset)} sizes={sizes} width={asset.width} height={asset.height} alt={asset.alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async"/>:null}
function Blocks({blocks,page,livePages,offset=0}:{blocks:NicheBlock[];page:NichePage;livePages:NichePage[];offset?:number}){return blocks.map((b,i)=>b.type==='heading'?(b.level===2?<h2 key={i} id={`section-${i+offset}`}>{b.text}</h2>:<h3 key={i}>{b.text}</h3>):b.type==='paragraph'?<p key={i}><LinkedText text={b.text} page={page} livePages={livePages}/></p>:b.type==='list'?<ul key={i}>{b.items.map((t,j)=><li key={j}><LinkedText text={t} page={page} livePages={livePages}/></li>)}</ul>:<figure key={i}><Picture page={page} asset={page.media.find(a=>a.id===b.assetId)} sizes="(max-width:800px) calc(100vw - 40px), 720px"/></figure>)}
function Header({page,livePages}:Props){const links=<>{[['nuomos-poreikis','Nuomos poreikis'],['gidai','Gidai']].map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`} aria-current={page.slug===slug?'page':undefined}>{label}</a>)}<a href="/kontaktai#zinute" className={styles.navAction}>Aprašyti projektą →</a></>;return <header className={styles.header}><div className={styles.headerInner}><a href="/" className={styles.brand} aria-label="Fasado pastoliai – pradžia"><Mark/><span>Fasado{' '}<strong>pastoliai</strong></span></a><nav className={styles.desktopNav} aria-label="Pagrindinė navigacija">{links}</nav><details className={styles.mobileNav}><summary><svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m6 4 4 4-4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="square"/></svg>Meniu</summary><nav aria-label="Mobilioji navigacija">{links}</nav></details></div></header>}
function GuideList({page,livePages}:Props){const guides=livePages.filter(p=>p.type==='guide'),prompts=['Kokius dydžius žinote?','Kas įtraukta į sumą?','Kas atsakingas už darbą?'];return <div className={styles.guideTable}>{guides.map((p,i)=><article key={p.id}><a href={nichePagePath(p)} className={styles.guidePhoto} tabIndex={-1} aria-hidden="true"><Picture page={p} asset={p.media[0]} sizes="(max-width:600px) calc(100vw - 40px), 220px"/></a><div><h2><a href={nichePagePath(p)}>{p.title}</a></h2><p>{p.description}</p></div><div className={styles.guideDecision}><p>{prompts[i]}</p><a href={nichePagePath(p)} className={styles.textLink}>Skaityti gidą →</a></div></article>)}{page.slug===''&&<a href="/gidai" className={styles.textLink}>Visi nuomos gidai →</a>}</div>}
function Close(){return <section className={styles.close}><h2>Jūsų fasadas. Aiškesnis poreikis.</h2><p>Vietovė, žinomi dydžiai, laikas ir paslaugos. Išankstinis tyrimas, be rezervacijos.</p><a href="/kontaktai#zinute" className={styles.button}>Aprašyti nuomos poreikį →</a></section>}
function Home(props:Props){const {page,livePages}=props,images=page.media.filter((a,i,all)=>all.findIndex(x=>x.alt===a.alt)===i),groups:{blocks:NicheBlock[];offset:number}[]=[];for(const [i,b]of page.body.entries()){if(b.type==='heading'&&b.level===2)groups.push({blocks:[b],offset:i});else if(groups.length)groups.at(-1)!.blocks.push(b)}return <>
 <section className={styles.hero}><div className={styles.heroIntro}><h1>{page.title}</h1><div><Blocks blocks={page.body.slice(0,2)} page={page} livePages={livePages}/><a href="/kontaktai#zinute" className={styles.button}>Aprašyti nuomos poreikį →</a></div></div><figure className={styles.heroPhoto}><Picture page={page} asset={images[0]} sizes="(max-width:800px) calc(100vw - 40px), (max-width:1240px) calc(100vw - 160px), 1080px" priority/><figcaption>Planuojamo fasado konteksto iliustracija</figcaption></figure><div className={styles.scopeStrip}><Blocks blocks={groups[0]?.blocks??[]} page={page} livePages={livePages} offset={groups[0]?.offset}/></div></section>
 <section className={styles.geometryIntro}><div><Blocks blocks={groups[1]?.blocks??[]} page={page} livePages={livePages} offset={groups[1]?.offset}/></div><figure><Picture page={page} asset={images[1]} sizes="(max-width:800px) calc(100vw - 40px), 360px"/><figcaption>Užrašykite tai, ką jau žinote</figcaption></figure></section><FacadeArea/>
 <section className={styles.compare}><Blocks blocks={groups[2]?.blocks??[]} page={page} livePages={livePages} offset={groups[2]?.offset}/></section><section className={styles.guides}><h2>Klausimai prieš nuomą</h2><GuideList {...props}/></section><section className={styles.prepare}><Blocks blocks={groups[3]?.blocks??[]} page={page} livePages={livePages} offset={groups[3]?.offset}/><a href="/nuomos-poreikis" className={styles.textLink}>Perskaityti pirmo etapo ribas →</a></section><Close/>
 </>}
function Inner(props:Props){const {page,pkg,livePages}=props,guide=page.type==='guide',index=page.slug==='gidai',contact=page.slug==='kontaktai',toc=page.body.flatMap((b,i)=>b.type==='heading'&&b.level===2?[{text:b.text,id:`section-${i}`}]:[]);return <>
 <section className={styles.pageIntro}><nav className={styles.breadcrumb} aria-label="Puslapio kelias">{nicheBreadcrumbs(pkg,page,livePages).map((b:{name:string;path:string},i:number,arr:unknown[])=><span key={b.path}>{i>0&&' / '}{i===arr.length-1?<span aria-current="page">{b.name}</span>:<a href={b.path}>{b.name}</a>}</span>)}</nav><h1>{page.title}</h1><p>{page.description}</p>{contact&&<a href="#zinute" className={styles.button}>Rašyti žinutę →</a>}{guide&&<div className={styles.byline}><ArticleMeta pkg={pkg} page={page} pages={livePages}/><p>Vietinė peržiūra: publikavimo data suplanuota, tikro paskelbimo neįrodo.</p></div>}</section>
 {index?<section className={styles.index}><GuideList {...props}/><div className={styles.indexCopy}><Blocks blocks={page.body} page={page} livePages={livePages}/></div></section>:<><div className={styles.readingLayout}><article className={styles.article}>{guide&&<figure className={styles.articlePhoto}><Picture page={page} asset={page.media[0]} sizes="(max-width:800px) calc(100vw - 40px), 720px" priority/><figcaption>Temos konteksto iliustracija</figcaption></figure>}<Blocks blocks={page.body} page={page} livePages={livePages}/>{!!page.externalLinks?.length&&<section id="saltiniai" className={styles.sources}><h2>Šaltiniai ir jų ribos</h2><ul>{page.externalLinks.map(s=><li key={s.url}><a href={s.url}>{s.label}</a><p>{s.reason}</p></li>)}</ul></section>}</article>{guide&&<aside className={styles.contents}><details><summary>Gido turinys</summary><nav aria-label="Gido turinys">{toc.map(t=><a key={t.id} href={`#${t.id}`}>{t.text}</a>)}<a href="#saltiniai">Šaltiniai</a></nav></details><p>Aiškus aprašas nepakeičia profesionalaus objekto įvertinimo.</p><a href="/kontaktai#zinute" className={styles.textLink}>Aprašyti savo poreikį →</a></aside>}</div>{page.slug==='fasado-matmenys'&&<FacadeArea/>}{contact&&<RentalInquiry/>}</>}
 {page.links.length>0&&!index&&<section className={styles.related}><h2>Tęskite savo klausimą</h2>{page.links.map(l=>{const target=livePages.find(p=>p.id===l.targetPageId);return target?<a key={target.id} href={nichePagePath(target)}>{l.label} →</a>:null})}</section>}{guide&&<Close/>}
 </>}
function Footer({pkg,livePages}:Props){return <footer className={styles.footer}><div className={styles.footerTop}><div><a href="/" className={styles.brand}><Mark/><span>Fasado{' '}<strong>pastoliai</strong></span></a><p>MB Pinet<br/><a href={`mailto:${pkg.site.contact.email}`}>{pkg.site.contact.email}</a></p></div><nav aria-label="Poraštės navigacija">{[['gidai','Gidai'],['kontaktai','Kontaktai'],['apie-projekta','Apie projektą'],['redakcija','Redakcija'],['privatumas','Privatumas'],['naudojimo-salygos','Naudojimo sąlygos']].map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`}>{label}</a>)}</nav></div><div className={styles.footerBottom}><p>{pkg.site.offer}</p><p>Mūsų verslas automatizuotas su <a href="https://verslomatika.lt/">verslomatika.lt</a></p></div></footer>}
export function FasadopastoliaiSite(props:Props){return <div className={styles.shell}><link rel="preload" as="font" type="font/woff2" href="/fonts/fasadopastoliai/archivo-700-latin.woff2" crossOrigin="anonymous"/><link rel="preload" as="font" type="font/woff2" href="/fonts/fasadopastoliai/archivo-700-latin-ext.woff2" crossOrigin="anonymous"/><link rel="stylesheet" href="/fonts/fasadopastoliai/fonts.css"/><link rel="icon" href="/favicon.svg"/><InterestTracking/><a className={styles.skip} href="#turinys">Pereiti prie turinio</a><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(props.pkg,props.page)}}/><Header {...props}/><main id="turinys" tabIndex={-1}>{props.page.type==='home'?<Home {...props}/>:<Inner {...props}/>}</main><Footer {...props}/></div>}
