'use client';
import {useState,useSyncExternalStore} from 'react';
import styles from './fasadopastoliai-site.module.css';
const subscribe=()=>()=>{};
const format=(v:number)=>new Intl.NumberFormat('lt-LT',{maximumFractionDigits:2}).format(v);
function value(s:string,max:number){const x=s.trim().replace(',','.');if(!/^\d+(?:\.\d+)?$/.test(x))return null;const n=Number(x);return Number.isFinite(n)&&n>0&&n<=max?n:null}
export function FacadeArea(){
 const ready=useSyncExternalStore(subscribe,()=>true,()=>false),[rows,setRows]=useState([['',''],['','']]),[result,setResult]=useState(''),[error,setError]=useState(''),[copied,setCopied]=useState('');
 function change(i:number,j:number,v:string){setRows(rows.map((r,k)=>k===i?r.map((x,l)=>l===j?v:x):r));setResult('');setError('');setCopied('')}
 function calculate(){let total=0,known=0,unknown=0;for(const [i,r]of rows.entries()){const hasL=!!r[0].trim(),hasH=!!r[1].trim(),l=hasL?value(r[0],200):null,h=hasH?value(r[1],100):null;if((hasL&&l===null)||(hasH&&h===null)){setError(`Siena ${i+1}: įrašykite teigiamą ilgį iki 200 m ir aukštį iki 100 m, su kableliu arba tašku. Tai ruošinio įvesties ribos, ne saugos ribos.`);setResult('');return}if(l===null||h===null){unknown++;continue}total+=l*h;known++}setError('');setResult(known?`${format(total)} m² – ${unknown?'tik žinomų sienų suma; dalis nežinoma':'įrašytų stačiakampių sienų geometrinė suma'}.\n${rows.map((r,i)=>`Siena ${i+1}: ${r[0].trim()&&r[1].trim()?r[0]+' × '+r[1]+' m':'matmenys nežinomi / nepilni'}`).join('\n')}\nNe pastolių kiekis, kaina ar montavimo projektas.`:'Plotas nežinomas: nėra pilnos sienos ilgio ir aukščio poros. Neįrašykite spėjamų dydžių.');setCopied('')}
 async function copy(){try{await navigator.clipboard.writeText(result);setCopied('Geometrijos aprašas nukopijuotas. Įklijuokite ir peržiūrėkite kontaktų žinutėje.')}catch{setCopied('Automatiškai nukopijuoti nepavyko. Pažymėkite ir nukopijuokite rezultatą ranka.')}}
 return <section className={styles.area} id="plotas" aria-labelledby="area-heading"><div><h2 id="area-heading">Fasado geometrijos ruošinys</h2><p>Įrašykite tik žinomų stačiakampių sienų dydžius. Langų neatimame; nežinomos dalies neprilyginame nuliui. Tai nėra pastolių komplektacijos, kainos ar saugos skaičiuotuvas.</p><p>Ilgis × aukštis, metrais. Galima rašyti kablelį arba tašką. Be JS žinomus dydžius užrašykite tiesiai kontaktų žinutėje.</p></div><div className={styles.areaSheet}>{rows.map((r,i)=><fieldset key={i}><legend>Siena {i+1}</legend><div className={styles.dimensions}><label htmlFor={`length-${i}`}>Ilgis, m<input id={`length-${i}`} inputMode="decimal" value={r[0]} maxLength={12} placeholder="Nežinau" onChange={e=>change(i,0,e.target.value)}/></label><label htmlFor={`height-${i}`}>Aukštis, m<input id={`height-${i}`} inputMode="decimal" value={r[1]} maxLength={12} placeholder="Nežinau" onChange={e=>change(i,1,e.target.value)}/></label></div></fieldset>)}<div className={styles.toolActions}><button type="button" disabled={!ready} onClick={calculate} className={styles.button}>Apskaičiuoti geometriją</button>{rows.length<4&&<button type="button" disabled={!ready} onClick={()=>{setRows([...rows,['','']]);setResult('');setError('');setCopied('')}} className={styles.secondaryButton}>Pridėti sieną</button>}</div><p role="alert" className={styles.error}>{error}</p><div role="status" className={styles.geometryResult}><p>{result||'Rezultatas bus rodomas čia. Nieko neišsiunčiame.'}</p>{result&&<button type="button" onClick={copy} className={styles.secondaryButton}>Nukopijuoti aprašą</button>}<p>{copied}</p></div><a href="/kontaktai#zinute" className={styles.textLink}>Pateikti nuomos poreikį →</a></div></section>
}
export function RentalInquiry(){
 const ready=useSyncExternalStore(subscribe,()=>true,()=>false),[message,setMessage]=useState(''),[notice,setNotice]=useState('');
 function prepare(){const v=(id:string)=>(document.getElementById(id) as HTMLInputElement|HTMLSelectElement)?.value.trim()||'Nežinau / reikia aptarti';setMessage(`Planinės fasado pastolių nuomos poreikis Vilniaus regione.\nVietovė: ${v('place')}.\nDarbai ir žinomi fasado matmenys: ${v('facade')}.\nPradžia ir trukmė: ${v('period')}.\nPaslaugų apimtis: ${v('services')}.\nAr rangovas jau organizuoja pastolius: ${v('contractor')}.\nSuprantu, kad tai išankstinis tyrimas, ne rezervacija ar pasiūlymo garantija.`);setNotice('Žinutė paruošta. Perskaitykite ir pataisykite; ji dar neišsiųsta.');document.getElementById('message')?.focus()}
 return <section className={styles.inquiry} id="poreikis"><form id="zinute" tabIndex={-1} action="/uzklausa" method="post" className={styles.form}><h2>Pateikite poreikį</h2><p>Išankstinis tyrimas, be nuomos rezervacijos. Vietinis bandymas: naudokite tik sintetinius duomenis; laiškų siuntimas išjungtas.</p><label htmlFor="name">Vardas</label><input id="name" name="name" autoComplete="given-name" minLength={2} maxLength={100} required/><label htmlFor="email">El. paštas</label><input id="email" name="email" type="email" autoComplete="email" maxLength={250} required/><label htmlFor="message">Jūsų žinutė <span>Mažiausiai 20 simbolių; vietovė, fasadas, laikas ir apimtis</span></label><textarea id="message" name="message" value={message} onChange={e=>setMessage(e.target.value)} minLength={20} maxLength={3000} rows={10} required/><div className={styles.trap} aria-hidden="true"><label htmlFor="website">Interneto svetainė</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><label className={styles.consent}><input name="consent" type="checkbox" value="yes" required/><span>Sutinku pateikti šią žinutę MB Pinet mano poreikiui nagrinėti. Susipažinau su <a href="/privatumas">privatumo tekstu</a>. Tai nėra rinkodaros prenumerata.</span></label><button type="submit" className={styles.button}>Pateikti išankstinį poreikį →</button></form><div className={styles.worksheet}><h2>Žinutės ruošinys</h2><p>Neprivalomas. Vietoje ruošinio galima rašyti tiesiai formoje. Paruošimas tik užpildo redaguojamą žinutę.</p><label htmlFor="place">Vietovė <span>Be tikslaus adreso</span></label><input id="place" maxLength={150} placeholder="Vilnius arba Vilniaus rajono vietovė"/><label htmlFor="facade">Darbai ir žinomi matmenys</label><input id="facade" maxLength={300} placeholder="Galite įklijuoti geometrijos aprašą"/><label htmlFor="period">Pageidaujama pradžia ir trukmė</label><input id="period" maxLength={180} placeholder="Jūsų planas, ne patvirtinta nuoma"/><label htmlFor="services">Reikalinga paslaugų apimtis</label><select id="services" defaultValue=""><option value="">Nežinau / reikia aptarti</option><option>Įranga ir transportas</option><option>Įranga, transportas, profesionalus montavimas ir išmontavimas</option><option>Reikia patikslinti su rangovu</option></select><label htmlFor="contractor">Ar rangovas jau pateikia pastolius?</label><select id="contractor" defaultValue=""><option value="">Nežinau</option><option>Ne, nuomą organizuoju pats</option><option>Taip / reikia išsiaiškinti jo apimtį</option></select><button type="button" onClick={prepare} disabled={!ready} className={styles.secondaryButton}>Paruošti žinutę →</button><p role="status" className={styles.status}>{notice}</p></div></section>
}
