/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages -- Host-aware SSR and shared responsive image families. */
import type {NichePackage,NichePage,NicheBlock,NicheMedia} from '@/lib/niche-sites';
import {nichePagePath} from '@/lib/niche-sites';
import {nicheJsonLd} from '@/lib/niche-seo';
import {nicheBreadcrumbs} from '@/lib/niche-schema-core.mjs';
import {imageSrcSet} from '@/lib/niche-media.mjs';
import {ArticleMeta} from './article-meta';
import {InterestTracking} from './interest-tracking';
import {LinkedText} from './linked-text';
import {ExcavationTool,InquiryForm} from './miniekskavatoriai-site.tools';
import styles from './miniekskavatoriai-site.module.css';
type Props={pkg:NichePackage;page:NichePage;livePages:NichePage[]};
function Mark(){return <svg width="32" height="32" viewBox="0 0 32 32" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M2 9h7v16h14V9h7M13 4v13m-3-3 3 3 3-3"/></svg>}
function Picture({page,asset,sizes,priority=false,className}:{page:NichePage;asset?:NicheMedia;sizes:string;priority?:boolean;className?:string}){return asset?<img className={className} src={asset.src} srcSet={imageSrcSet(page.media,asset)} sizes={sizes} width={asset.width} height={asset.height} alt={asset.alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async"/>:null}
function Blocks({blocks,page,livePages,offset=0}:{blocks:NicheBlock[];page:NichePage;livePages:NichePage[];offset?:number}){return blocks.map((b,i)=>b.type==='paragraph'?<p key={i}><LinkedText text={b.text} page={page} livePages={livePages}/></p>:b.type==='heading'?(b.level===2?<h2 key={i} id={`section-${offset+i}`}>{b.text}</h2>:<h3 key={i}>{b.text}</h3>):b.type==='list'?<ul key={i}>{b.items.map((t,j)=><li key={j}><LinkedText text={t} page={page} livePages={livePages}/></li>)}</ul>:<figure key={i}><Picture page={page} asset={page.media.find(a=>a.id===b.assetId)} sizes="(max-width: 800px) calc(100vw - 40px), 760px"/></figure>)}
function Header({page,livePages}:Props){const nav=<>{[['transejos-kasimas','Tūris ir ruošinys'],['su-operatoriumi','Kasimo poreikis'],['gidai','Gidai']].map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`} aria-current={page.slug===slug?'page':undefined}>{label}</a>)}<a className={styles.navAction} href="/kontaktai#poreikis">Aprašyti darbą →</a></>;return <header className={styles.header}><div className={styles.headerInner}><a href="/" className={styles.brand} aria-label="Miniekskavatoriai – pradžia"><Mark/><span>miniekskavatoriai<span className={styles.brandLt}>.lt</span></span></a><nav className={styles.desktopNav} aria-label="Pagrindinė navigacija">{nav}</nav><details className={styles.mobileNav}><summary>Meniu</summary><nav aria-label="Mobilioji navigacija">{nav}</nav></details></div></header>}
function GuideList({livePages,page}:Props){const Heading=page.slug==='gidai'?'h2':'h3';return <div className={styles.guideList}>{livePages.filter(p=>p.type==='guide').map(p=><article key={p.id}><a href={nichePagePath(p)} className={styles.guidePhoto} tabIndex={-1} aria-hidden="true"><Picture page={p} asset={p.media[0]} sizes="(max-width: 700px) calc(100vw - 40px), 290px"/></a><div><Heading><a href={nichePagePath(p)}>{p.title}</a></Heading><p>{p.description}</p><a className={styles.textLink} href={nichePagePath(p)}>Skaityti gidą →</a></div></article>)}</div>}
function Diagram(){return <figure className={styles.diagram}><svg viewBox="0 0 450 265" role="img" aria-labelledby="trench-title trench-desc"><title id="trench-title">Stačiakampės tranšėjos geometrija</title><desc id="trench-desc">Ilgis, plotis ir gylis dauginami. Tai formulės schema, ne kasimo profilis.</desc><path d="M70 84 210 26 382 77 245 135Z" fill="#f3ad76"/><path d="M70 84v100l175 53V135Z" fill="#cc6236"/><path d="m245 135 137-58v102l-137 58Z" fill="#994424"/><g fill="none" stroke="#1b2c34" strokeWidth="2"><path d="M70 84 210 26 382 77v102l-137 58-175-53V84l175 51 137-58M245 135v102M50 84v100M210 10 382 61M84 220l146 44"/></g><g fontSize="17" fill="#1b2c34"><text x="14" y="139">D</text><text x="295" y="30">W</text><text x="145" y="252">L</text></g></svg><figcaption>V = L × W × D<br/>Geometrinė schema, ne kasimo instrukcija</figcaption></figure>}
function Home(props:Props){const {page,livePages}=props;const groups:{blocks:NicheBlock[];offset:number}[]=[];for(const [i,b]of page.body.entries()){if(b.type==='heading'&&b.level===2)groups.push({blocks:[b],offset:i});else if(groups.length)groups.at(-1)!.blocks.push(b)}const images=page.media.filter((a,i,all)=>all.findIndex(x=>x.alt===a.alt)===i);return <><section className={styles.hero}><div className={styles.heroGrid}><div className={styles.heroCopy}><h1>{page.title}</h1><Blocks blocks={page.body.slice(0,1)} page={page} livePages={livePages}/><a className={styles.heroLink} href="/su-operatoriumi">Kokį poreikį registruojame →</a><div className={styles.pilot}><Blocks blocks={page.body.slice(1,2)} page={page} livePages={livePages}/></div></div><ExcavationTool compact/></div></section><figure className={styles.panorama}><Picture page={page} asset={images[0]} sizes="100vw" priority/><figcaption>Planuojamo darbo konteksto iliustracija</figcaption></figure><section className={styles.scope}><Diagram/><div><Blocks blocks={groups[0]?.blocks??[]} offset={groups[0]?.offset} page={page} livePages={livePages}/><a className={styles.textLink} href="/nuomos-kainos-sudetis">Kaip palyginti visą kainos apimtį →</a></div></section><section className={styles.access}><div><Picture page={page} asset={images[1]} sizes="(max-width: 800px) calc(100vw - 40px), 620px"/><p className={styles.caption}>Pradėkite nuo siauriausios vietos</p></div><div><Blocks blocks={groups[1]?.blocks??[]} offset={groups[1]?.offset} page={page} livePages={livePages}/><a className={styles.textLink} href="/pravaziavimo-plotis">Pravažiavimo patikros sąrašas →</a><div className={styles.safety}><Blocks blocks={groups[2]?.blocks??[]} offset={groups[2]?.offset} page={page} livePages={livePages}/><a href="https://www.eso.lt/namams/elektra/kasimo-darbai/3762">ESO kasimo darbų informacija ↗</a></div></div></section><section className={styles.guides}><div className={styles.sectionTitle}><h2>Aiškiau prieš susitarimą</h2><a href="/gidai">Visi gidai →</a></div><GuideList {...props}/></section><Callout/></>}
function Callout(){return <section className={styles.callout}><div><h2>Aprašykite savo tranšėją.</h2><p>Vietovė, matmenys, laikas ir neaiškumai. Išankstinis poreikis Kauno regionui; tai nėra užsakymas.</p></div><a className={styles.button} href="/kontaktai#poreikis">Pateikti poreikį →</a></section>}
function Inner(props:Props){const {page,pkg,livePages}=props,isGuide=page.type==='guide',isIndex=page.slug==='gidai',isTool=page.slug==='transejos-kasimas';const toc=page.body.flatMap((b,i)=>b.type==='heading'&&b.level===2?[{text:b.text,id:`section-${i}`}]:[]);return <><section className={styles.pageIntro}><nav className={styles.breadcrumb} aria-label="Puslapio kelias">{nicheBreadcrumbs(pkg,page,livePages).map((b:{name:string;path:string},i:number,arr:unknown[])=><span key={b.path}>{i>0&&' / '}{i===arr.length-1?<span aria-current="page">{b.name}</span>:<a href={b.path}>{b.name}</a>}</span>)}</nav><h1>{page.title}</h1><p>{page.description}</p>{isGuide&&<ArticleMeta pkg={pkg} page={page} pages={livePages} className={styles.byline}/>}</section>{isTool&&<div className={styles.fullTool}><ExcavationTool email={pkg.site.contact.email}/></div>}{isIndex?<section className={styles.index}><div className={styles.indexText}><Blocks blocks={page.body} page={page} livePages={livePages}/></div><GuideList {...props}/></section>:<div className={`${styles.readingLayout} ${isGuide?styles.guideLayout:''}`}><article className={styles.article}>{isGuide&&<figure className={styles.articleFigure}><Picture page={page} asset={page.media[0]} sizes="(max-width: 800px) calc(100vw - 40px), 760px" priority/><figcaption>Temos iliustracija, ne atliktas darbas</figcaption></figure>}<Blocks blocks={page.body} page={page} livePages={livePages}/>{!!page.externalLinks?.length&&<section id="saltiniai" className={styles.sources}><h2>Šaltiniai ir jų ribos</h2><ul>{page.externalLinks.map(s=><li key={s.url}><a href={s.url}>{s.label}</a><p>{s.reason}</p></li>)}</ul></section>}</article>{isGuide&&<aside className={styles.contents}><h2>Šiame gide</h2><nav aria-label="Gido turinys">{toc.map(t=><a key={t.id} href={`#${t.id}`}>{t.text}</a>)}<a href="#saltiniai">Šaltiniai</a></nav><a className={styles.textLink} href="/kontaktai#poreikis">Aprašyti savo darbą →</a></aside>}</div>}{page.slug==='kontaktai'&&<div className={styles.fullTool}><InquiryForm email={pkg.site.contact.email}/></div>}{page.links.length>0&&!isIndex&&<section className={styles.related}><h2>Kitas naudingas žingsnis</h2>{page.links.map(l=>{const t=livePages.find(p=>p.id===l.targetPageId);return t?<a className={styles.textLink} key={t.id} href={nichePagePath(t)}>{l.label} →</a>:null})}</section>}{isGuide&&<Callout/>}</>}
function Footer({pkg,livePages}:Props){return <footer className={styles.footer}><div className={styles.footerTop}><div><a className={styles.brand} href="/"><Mark/><span>miniekskavatoriai.lt</span></a><p>MB Pinet<br/><a href={`mailto:${pkg.site.contact.email}`}>{pkg.site.contact.email}</a></p></div><nav aria-label="Poraštės navigacija">{[['gidai','Gidai'],['kontaktai','Kontaktai'],['apie-projekta','Apie projektą'],['redakcija','Redakcija'],['privatumas','Privatumas'],['naudojimo-salygos','Naudojimo sąlygos']].map(([slug,title])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`}>{title}</a>)}</nav></div><div className={styles.footerBottom}><p>{pkg.site.offer}</p><p>Mūsų verslas automatizuotas su <a href="https://verslomatika.lt/" rel="noopener noreferrer">verslomatika.lt</a></p></div></footer>}
export function MiniekskavatoriaiSite(props:Props){return <div className={styles.shell}><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='%231b2c34'/%3E%3Cpath d='M4 9h5v16h14V9h5M16 4v13m-3-3 3 3 3-3' fill='none' stroke='%23f2a36c' stroke-width='2'/%3E%3C/svg%3E"/><InterestTracking/><a href="#turinys" className={styles.skip}>Pereiti prie turinio</a><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(props.pkg,props.page)}}/><Header {...props}/><main id="turinys" tabIndex={-1}>{props.page.type==='home'?<Home {...props}/>:<Inner {...props}/>}</main><Footer {...props}/></div>}
