/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages -- Native SSR catalogue and optimized supplier photos. */
import type { NicheBlock, NichePackage, NichePage, NicheMedia } from "@/lib/niche-sites";
import { nichePagePath } from "@/lib/niche-sites";
import { nicheJsonLd } from "@/lib/niche-seo";
import { nicheNetworkContact } from "@/lib/niche-network";
import { nicheBreadcrumbs } from "@/lib/niche-schema-core.mjs";
import { imageSrcSet, responsiveImageVariants, visibleImageCredit } from "@/lib/niche-media.mjs";
import { LinkedText } from "./linked-text";
import { ArticleMeta } from "./article-meta";
import { InterestTracking } from "./interest-tracking";
import { AddToInquiry, InquiryCount, InquiryForm } from "./promedical-inquiry";
import s from "./promedical-site.module.css";

type Query = { q?: string; category?: string; p?: string };
const primaryGroups = ["zakladni-voziky", "voziky-s-prislusenstvim", "iso-modul-system", "skrine", "specialni-voziky", "produkty-pro-sterilizaci", "zdravotnicky-nabytek-prehled-hlavni", "prislusenstvi"];
function Arrow() { return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg>; }
function SearchIcon() { return <svg viewBox="0 0 24 24" width="20" height="20" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" strokeWidth="1.7"/><path d="m16 16 4 4" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round"/></svg>; }
function Brand() { return <a href="/" className={s.brand} aria-label="Promedical – pradinis puslapis"><img className={s.brandLogo} src="/brand/promedical/logo-v2-360.webp" srcSet="/brand/promedical/logo-v2-360.webp 360w, /brand/promedical/logo-v2-640.webp 640w" sizes="(max-width: 720px) 205px, 244px" width="640" height="213" alt="Promedical" decoding="async"/></a>; }
function Photo({ page, asset = page.media[0], eager = false, sizes = "(max-width: 720px) calc(100vw - 40px), 380px" }: { page: NichePage; asset?: NicheMedia; eager?: boolean; sizes?: string }) { return asset ? <img src={asset.src} srcSet={imageSrcSet(page.media, asset)} sizes={sizes} alt={asset.alt} width={asset.width} height={asset.height} loading={eager ? "eager" : "lazy"} fetchPriority={eager ? "high" : undefined} decoding="async"/> : null; }
function sku(page: NichePage) { return page.intent.startsWith("Katalogo kodas: ") ? page.intent.split(" | ")[0].slice("Katalogo kodas: ".length) : page.slug.split("/").at(-1)?.toUpperCase() || ""; }
function isCategory(p: NichePage) { return p.slug.startsWith("kategorijos/"); }
function isProduct(p: NichePage) { return p.type === "product" && p.slug.startsWith("produktai/"); }
function groupPages(pages: NichePage[]) { const cats = pages.filter(isCategory); return primaryGroups.map(id => cats.find(p => p.slug === `kategorijos/${id}`)).filter(Boolean) as NichePage[]; }
function Header({ q }: { q?: string }) { return <><a className={s.skip} href="#turinys">Pereiti prie turinio</a><header className={s.header}><div className={s.headerTop}><Brand/><form action="/produktai" role="search" className={s.search}><label className={s.srOnly} htmlFor="catalog-search">Ieškoti produktų</label><input id="catalog-search" name="q" defaultValue={q || ""} maxLength={100} placeholder="Ieškoti produkto arba katalogo kodo"/><button aria-label="Ieškoti"><SearchIcon/></button></form><a href="/kontaktai" className={s.headerRequest}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M8 4h8v3H8zM7 5H5v16h14V5h-2M8 11h8M8 15h6" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/></svg><span>Užklausos sąrašas</span><InquiryCount/></a></div><div className={s.navRow}><nav aria-label="Pagrindinė navigacija"><a className={s.catalogNav} href="/produktai">Produktų katalogas <Arrow/></a><a href="/gidai">Pasirinkimo gidai</a><a href="/apie-projekta">Apie mus</a><a href="/kontaktai">Kontaktai</a></nav><span className={s.maker}>Atstovaujame <strong>KLARO</strong></span><details className={s.mobileMenu}><summary>Meniu <svg width="20" height="20" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16" stroke="currentColor" strokeWidth="1.7"/></svg></summary><nav aria-label="Mobilioji navigacija"><a href="/produktai">Produktų katalogas</a><a href="/gidai">Pasirinkimo gidai</a><a href="/apie-projekta">Apie mus</a><a href="/kontaktai">Kontaktai ir užklausa</a></nav></details></div></header></>; }
function Crumbs({ pkg, page, pages }: { pkg: NichePackage; page: NichePage; pages: NichePage[] }) { return <nav className={s.crumbs} data-niche-breadcrumbs aria-label="Puslapio kelias">{nicheBreadcrumbs(pkg, page, pages).map((v: {name:string;path:string}, i:number, all:{name:string;path:string}[]) => <span key={v.path}>{i > 0 && <span aria-hidden="true">/</span>}{i === all.length - 1 ? <span aria-current="page">{v.name}</span> : <a href={v.path}>{v.name}</a>}</span>)}</nav>; }
function BodyFigure({ page, assetId }: { page: NichePage; assetId: string }) {
  const asset = page.media.find(m => m.id === assetId);
  if (!asset) return null;
  const credit = visibleImageCredit(asset);
  return <figure className={s.bodyImage}><a href={asset.src} target="_blank" rel="noopener noreferrer"><Photo page={page} asset={asset} sizes="(max-width: 720px) calc(100vw - 40px), 760px"/></a><figcaption>{credit && <span>{credit}</span>}<a href={asset.src} target="_blank" rel="noopener noreferrer">Peržiūrėti vaizdą didesniu dydžiu</a></figcaption></figure>;
}
function Blocks({ page, pages, body = page.body }: { page: NichePage; pages: NichePage[]; body?: NicheBlock[] }) { return <>{body.map((b, i) => b.type === "paragraph" ? <p key={i}><LinkedText text={b.text} page={page} livePages={pages}/></p> : b.type === "heading" ? b.level === 2 ? <h2 id={`skyrius-${i}`} key={i}>{b.text}</h2> : <h3 key={i}>{b.text}</h3> : b.type === "list" ? <ul key={i}>{b.items.map((t,j) => <li key={j}><LinkedText text={t} page={page} livePages={pages}/></li>)}</ul> : <BodyFigure key={i} page={page} assetId={b.assetId}/>)}</>; }
function Sources({ page }: { page: NichePage }) { return page.externalLinks?.length ? <section className={s.sources}><h2>Šaltiniai ir dokumentai</h2>{page.externalLinks.map(v => <div key={v.url}><a href={v.url} target="_blank" rel="noopener noreferrer">{v.label} <Arrow/></a><p>{v.reason}</p></div>)}</section> : null; }
function ProductCard({ product }: { product: NichePage }) { return <article className={s.productCard}><a className={s.productImage} href={nichePagePath(product)} tabIndex={-1} aria-hidden="true"><Photo page={product} sizes="(max-width: 520px) calc(100vw - 40px), (max-width: 720px) calc((100vw - 55px) / 2), (max-width: 1050px) calc((100vw - 63px) / 2), 300px"/></a><span className={s.sku}>KLARO · {sku(product)}</span><h3><a href={nichePagePath(product)}>{product.title}</a></h3><p>{product.description}</p><a className={s.productLink} href={nichePagePath(product)}>Peržiūrėti produktą <Arrow/></a></article>; }
function GuideCards({ pages }: { pages: NichePage[] }) { return <div className={s.guides}>{pages.filter(p => p.type === "guide").map(p => <article key={p.id}><a href={nichePagePath(p)} className={s.guidePhoto} tabIndex={-1} aria-hidden="true"><Photo page={p}/></a><h3><a href={nichePagePath(p)}>{p.title}</a></h3><p>{p.description}</p><a href={nichePagePath(p)} className={s.textLink}>Skaityti gidą <Arrow/></a></article>)}</div>; }
function Home({ page, pages }: { page: NichePage; pages: NichePage[] }) {
  const products = pages.filter(isProduct); const cats = groupPages(pages); const featuredCodes = ["zv1253n-pz", "ut5201", "nerez1002is", "nerez2201"];
  const featured = featuredCodes.map(id => products.find(p => p.slug === `produktai/${id}`)).filter(Boolean) as NichePage[];
  const hero = featured[0] || page;
  return <><section className={s.hero}><div className={s.heroCopy}><h1>{page.title.replace(/\s*\|\s*Promedical$/u, "")}</h1><p>{page.description}</p><div className={s.heroActions}><a href="/produktai" className={s.primary}>Peržiūrėti katalogą <Arrow/></a><a href="/kontaktai" className={s.secondary}>Pateikti poreikį</a></div><div className={s.heroBottom}><span>Ligoninėms</span><span>Poliklinikoms</span><span>Slaugos įstaigoms</span></div></div><div className={s.heroProduct}><Photo page={hero} eager sizes="(max-width: 720px) calc(100vw - 40px), 600px"/>{isProduct(hero) && <a className={s.heroCaption} href={nichePagePath(hero)}><span>KLARO <strong>{sku(hero)}</strong></span><span>Modelio informacija <Arrow/></span></a>}</div></section>
    <section className={s.section}><div className={s.sectionHeading}><div><h2>Įranga jūsų kasdieniam darbui</h2><p>Raskite įrangą pagal paskirtį ir darbo aplinką.</p></div><a className={s.textLink} href="/produktai">Visas katalogas <Arrow/></a></div><div className={s.categoryGrid}>{cats.map(c => <a key={c.id} className={s.categoryTile} href={nichePagePath(c)}><div className={s.categoryImage}><Photo page={c} sizes="(max-width: 720px) 135px, (max-width: 1050px) 145px, 175px"/></div><h3>{c.title}</h3><Arrow/></a>)}</div></section>
    <section className={s.section}><article className={s.article}><Blocks page={page} pages={pages}/></article></section>
    <section className={s.selectionSection}><div><h2>Nuo vieno vežimėlio<br/>iki skyriaus įrangos.</h2><p>Pasirinkite katalogo modelius ir nurodykite reikiamus kiekius. Priedus, komplektaciją bei tiekimo sąlygas aptarsime pagal jūsų įstaigos poreikį.</p><a href="/kontaktai" className={s.primary}>Parengti užklausą <Arrow/></a></div><div className={s.selectionSteps}><div><strong>Pasirinkite modelius</strong><p>Katalogo kodai ir techniniai duomenys padės tiksliai įvardyti poreikį.</p></div><div><strong>Nurodykite kiekius ir reikalavimus</strong><p>Surinkite skyriaus ar visos įstaigos įrangą vienoje užklausoje.</p></div><div><strong>Aptarkime komplektaciją</strong><p>Kaina ir tiekimo sąlygos suderinamos individualiai.</p></div></div></section>
    {featured.length > 0 && <section className={s.section}><div className={s.sectionHeading}><h2>Susipažinkite su „Klaro“ įranga</h2><a className={s.textLink} href="/produktai">Rasti savo modelį <Arrow/></a></div><div className={s.productGrid}>{featured.map(p => <ProductCard product={p} key={p.id}/>)}</div></section>}
    {pages.some(p=>p.type==="guide")&&<section className={s.section}><div className={s.sectionHeading}><div><h2>Aiškesnis pasirinkimas įstaigai</h2><p>Praktiniai gidai prieš rengiant įrangos užklausą.</p></div><a href="/gidai" className={s.textLink}>Visi gidai <Arrow/></a></div><GuideCards pages={pages.filter(p=>p.type==="guide").slice(0,6)}/></section>}
  </>;
}
function Catalog({ page, pages, query }: { page: NichePage; pages: NichePage[]; query: Query }) {
  const allProducts = pages.filter(isProduct); const categories = pages.filter(isCategory); const selected = isCategory(page) ? page : categories.find(c => c.slug.slice("kategorijos/".length) === query.category);
  const selectedIds = new Set(selected ? [selected.id] : []); if(selected){let changed=true;while(changed){changed=false;for(const c of categories)if(!selectedIds.has(c.id)&&c.links.some(l=>selectedIds.has(l.targetPageId))){selectedIds.add(c.id);changed=true;}}}
  const normalize = (v:string) => v.toLocaleLowerCase("lt-LT").normalize("NFD").replace(/[\u0300-\u036f]/g, ""); const term = normalize((query.q || "").slice(0,100));
  const filtered = allProducts.filter(p => (!selected || selectedIds.has(p.id) || p.links.some(l => selectedIds.has(l.targetPageId))) && (!term || normalize(`${p.title} ${sku(p)} ${p.description}`).includes(term)));
  const requested = Number(query.p); const totalPages = Math.max(1, Math.ceil(filtered.length / 24)); const current = Number.isInteger(requested) ? Math.max(1,Math.min(totalPages,requested)) : 1; const shown = filtered.slice((current - 1)*24,current*24);
  function url(p:number) { const v = new URLSearchParams(); if(query.q)v.set("q",query.q); if(query.category && !isCategory(page))v.set("category",query.category); if(p>1)v.set("p",String(p)); return nichePagePath(page)+(v.size ? `?${v}` : ""); }
  const subgroup = selected ? categories.filter(c=>c.links.some(l=>l.targetPageId===selected.id)) : [];
  const categoryIds = new Set(categories.map(c => c.id)); const rootGroups=categories.filter(c=>!c.links.some(l=>categoryIds.has(l.targetPageId)));
  return <><section className={s.catalogIntro}><h1>{page.title.replace(/\s*\|\s*Promedical$/u, "")}</h1><p>{page.description}</p></section><div className={s.catalogLayout}><aside className={s.catalogSidebar}><h2>Produktų grupės</h2><a href="/produktai" className={!selected ? s.activeCategory : ""}>Visi produktai <span>{allProducts.length}</span></a>{groupPages(pages).map(c => <a key={c.id} href={nichePagePath(c)} className={selected?.id === c.id ? s.activeCategory : ""}>{c.title}<Arrow/></a>)}<details><summary>Kitos produktų grupės</summary>{rootGroups.filter(c => !primaryGroups.includes(c.slug.split("/").at(-1)!)).map(c => <a href={nichePagePath(c)} key={c.id}>{c.title}</a>)}</details></aside><section className={s.catalogResults} aria-label="Produktų paieškos rezultatai"><h2 className={s.srOnly}>Produktų paieškos rezultatai</h2><form action={nichePagePath(page)} className={s.catalogFilters}><label>Ieškoti šiame kataloge<input name="q" defaultValue={query.q || ""} maxLength={100} placeholder="Pavadinimas arba kodas"/></label><button className={s.primary}>Ieškoti <SearchIcon/></button></form>{subgroup.length > 0 && <div className={s.subgroups}>{subgroup.map(c=><a href={nichePagePath(c)} key={c.id}>{c.title} <Arrow/></a>)}</div>}<div className={s.resultCount}><p>{query.q ? `„${query.q.slice(0,100)}“ · ` : ""}{filtered.length} produktų</p><span>{filtered.length > 0 ? `${(current-1)*24+1}–${Math.min(current*24,filtered.length)}` : "0"}</span></div>{shown.length ? <div className={s.productGrid}>{shown.map(p => <ProductCard product={p} key={p.id}/>)}</div> : <div className={s.empty}><h2>Pagal šią paiešką produktų neradome</h2><p>Patikrinkite katalogo kodą arba ieškokite bendresnio pavadinimo. Poreikį galite aprašyti ir be konkretaus modelio.</p><a href="/produktai" className={s.textLink}>Visas katalogas <Arrow/></a><a href="/kontaktai" className={s.textLink}>Pateikti poreikį <Arrow/></a></div>}{totalPages > 1 && <nav className={s.pagination} aria-label="Katalogo puslapiai">{current>1 && <a href={url(current-1)}>Ankstesnis</a>}<span>Puslapis {current} iš {totalPages}</span>{current<totalPages && <a href={url(current+1)}>Kitas <Arrow/></a>}</nav>}</section></div>{page.slug==="produktai"&&<section className={s.section}><article className={s.article}><Blocks page={page} pages={pages}/></article></section>}</>;
}
function Product({ page, pages }: { page: NichePage; pages: NichePage[] }) {
  const related = page.links.map(l=>pages.find(p=>p.id===l.targetPageId)).filter(p=>p&&isProduct(p)) as NichePage[];
  const graph = { "@context":"https://schema.org", "@type":"Product", name:page.title, sku:sku(page), brand:{"@type":"Brand",name:"Klaro"}, manufacturer:{"@type":"Organization",name:"Klaro, spol. s r.o."}, description:page.description, ...(page.media[0] ? {image:`https://promedical.lt${page.media[0].src}`} : {}) };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph).replace(/</g,"\\u003c")}}/><section className={s.productDetail}><div className={s.gallery}><div className={s.mainPhoto}><Photo page={page} eager sizes="(max-width: 720px) calc(100vw - 40px), 560px"/></div>{page.media.some((m,i,a)=>i>0 && !a.slice(0,i).some(v=>v.alt===m.alt)) && <details className={s.morePhotos}><summary>Daugiau produkto nuotraukų</summary><div>{page.media.filter((m,i,a)=>i>0 && !a.slice(0,i).some(v=>v.alt===m.alt)).map(m=><a href={m.src} key={m.id} target="_blank" rel="noopener noreferrer"><Photo page={page} asset={m}/></a>)}</div></details>}</div><div className={s.productSummary}><span className={s.sku}>KLARO · {sku(page)}</span><h1>{page.title.replace(/\s*\|\s*Promedical$/u, "")}</h1><p className={s.productLead}>{page.description}</p><dl className={s.orderFacts}><div><dt>Katalogo kodas</dt><dd>{sku(page)}</dd></div><div><dt>Gamintojas</dt><dd>Klaro, Čekija</dd></div><div><dt>Kaina ir komplektacija</dt><dd>Pagal individualų pasiūlymą</dd></div></dl><AddToInquiry sku={sku(page)} title={page.title} path={nichePagePath(page)}/><p className={s.productNote}>Norimą komplektaciją, priedus ir spalvas nurodykite užklausoje. Produktų vaizdai gali rodyti papildomus priedus.</p>{/išpardavim|rezervuot|nuolaid/i.test(page.title) && <p className={s.productNote}>Modelio pavadinime išsaugotas gamintojo pasiūlymo žymėjimas. Dabartines pardavimo ir tiekimo sąlygas patvirtinsime atsakydami į jūsų užklausą.</p>}</div></section><div className={s.productBody}><article className={s.article}><Blocks page={page} pages={pages}/><Sources page={page}/></article><aside className={s.productAside}><h2>Ruošiate įstaigos pirkimą?</h2><p>Pasirinktus modelius ir kiekius sujunkite į vieną užklausą. Nurodykite skyrių, įrangos paskirtį ir reikalavimus.</p><a href="/kontaktai" className={s.primary}>Peržiūrėti užklausą <Arrow/></a>{pages.some(p => p.slug === "gidai/irangos-pirkimo-uzklausa") && <a href="/gidai/irangos-pirkimo-uzklausa" className={s.textLink}>Pirkimo užklausos gidas <Arrow/></a>}</aside></div>{related.length>0 && <section className={s.section}><h2>Susiję produktai ir priedai</h2><div className={s.productGrid}>{related.slice(0,8).map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</>;
}
function Content({ pkg,page,pages }: {pkg:NichePackage;page:NichePage;pages:NichePage[]}) {
  const bodyAssets = new Set(page.body.filter(b => b.type === "image").map(b => b.assetId));
  const hero = page.media.find(asset => !responsiveImageVariants(page.media, asset).some((variant: NicheMedia) => bodyAssets.has(variant.id)));
  const credit = hero && visibleImageCredit(hero);
  return <><div className={s.readingHeader}><h1>{page.title.replace(/\s*\|\s*Promedical$/u, "")}</h1><p>{page.description}</p>{page.type==="guide"&&<ArticleMeta pkg={pkg} page={page} pages={pages} className={s.articleMeta}/>}</div>{page.slug==="gidai" ? <section className={s.section}><GuideCards pages={pages}/><article className={s.article}><Blocks page={page} pages={pages}/></article></section> : <div className={s.readingLayout}><article className={s.article}>{page.type==="guide"&&hero&&<figure className={s.articleHero}><Photo page={page} asset={hero} eager sizes="(max-width: 720px) calc(100vw - 40px), 760px"/>{credit&&<figcaption>{credit}</figcaption>}</figure>}<Blocks page={page} pages={pages}/><Sources page={page}/>{page.slug==="kontaktai"&&<InquiryForm email={pkg.site.contact.email}/>}</article>{page.type==="guide"&&<aside className={s.readingAside}><h2>Pasirinkite įrangą</h2><p>Modelius ir jų techninius duomenis rasite produktų kataloge.</p><a href="/produktai" className={s.primary}>Atverti katalogą <Arrow/></a><a href="/kontaktai" className={s.textLink}>Parengti užklausą <Arrow/></a></aside>}</div>}</>;
}
function Footer({ pkg }: {pkg:NichePackage}) { return <footer className={s.footer}><div className={s.footerMain}><div><Brand/><p>{pkg.site.offer}</p><span className={s.footerMaker}>Mūsų atstovaujamas gamintojas <strong>KLARO</strong></span></div><div><h2>Įranga</h2><a href="/produktai">Produktų katalogas</a><a href="/gidai">Pasirinkimo gidai</a><a href="/kontaktai">Užklausos sąrašas</a></div><div><h2>{nicheNetworkContact(pkg.siteId).operatorName}</h2><a href={`mailto:${pkg.site.contact.email}`} data-interest="email_click">{pkg.site.contact.email}</a>{pkg.site.contact.phone && <a href={`tel:${pkg.site.contact.phone.replace(/\s/g,"")}`} data-interest="phone_click">{pkg.site.contact.phone}</a>}<a href="/apie-projekta">Apie mus</a><a href="/redakcija">Turinio rengimas</a></div></div><div className={s.footerBottom}><span>© 2026 Promedical</span><div><a href="/privatumas">Privatumas</a><a href="/naudojimo-salygos">Naudojimo sąlygos</a></div><a href="https://verslomatika.lt">Mūsų verslas automatizuotas su verslomatika.lt</a></div></footer>; }
export function PromedicalSite({pkg,page,livePages,query={}}:{pkg:NichePackage;page:NichePage;livePages:NichePage[];query?:Query}) { return <div className={s.shell}><Header q={query.q}/><main id="turinys" tabIndex={-1}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(pkg,page,livePages)}}/>{page.type!=="home"&&<Crumbs pkg={pkg} page={page} pages={livePages}/>}<div className={s.content}>{page.type==="home" ? <Home page={page} pages={livePages}/> : isProduct(page) ? <Product page={page} pages={livePages}/> : page.slug==="produktai"||isCategory(page) ? <Catalog page={page} pages={livePages} query={query}/> : <Content pkg={pkg} page={page} pages={livePages}/>}</div></main><Footer pkg={pkg}/><InterestTracking/></div>; }
