/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages -- Host-aware routing and approved responsive media. */
import type {NichePackage,NichePage,NicheBlock,NicheMedia} from '@/lib/niche-sites';
import {nichePagePath} from '@/lib/niche-sites';
import {nicheJsonLd} from '@/lib/niche-seo';
import {nicheBreadcrumbs} from '@/lib/niche-schema-core.mjs';
import {imageSrcSet} from '@/lib/niche-media.mjs';
import {LinkedText} from './linked-text';
import {ArticleMeta} from './article-meta';
import {InterestTracking} from './interest-tracking';
import {WindowInquiry} from './roletaiklaipedoje-site.tools';
import s from './roletaiklaipedoje-site.module.css';
type Props={pkg:NichePackage;page:NichePage;livePages:NichePage[]};
function Mark(){return <svg width="36" height="42" viewBox="0 0 36 42" fill="none" aria-hidden="true"><path d="M3 39V3h30v36H3ZM18 3v36M3 12h30M3 19h30M3 26h30" stroke="currentColor" strokeWidth="1.5"/><path d="M5 31h11M20 31h11" stroke="currentColor" strokeWidth="3"/></svg>}
function Photo({page,asset=page.media[0],priority=false,sizes='(max-width: 760px) calc(100vw - 40px), 760px'}:{page:NichePage;asset?:NicheMedia;priority?:boolean;sizes?:string}){return asset?<img src={asset.src} srcSet={imageSrcSet(page.media,asset)} sizes={sizes} width={asset.width} height={asset.height} alt={asset.alt} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':undefined} decoding="async"/>:null}
function Blocks({blocks,page,livePages,offset=0}:{blocks:NicheBlock[];page:NichePage;livePages:NichePage[];offset?:number}){return blocks.map((b,i)=>b.type==='heading'?(b.level===2?<h2 key={i} id={`section-${i+offset}`}>{b.text}</h2>:<h3 key={i}>{b.text}</h3>):b.type==='paragraph'?<p key={i}><LinkedText text={b.text} page={page} livePages={livePages}/></p>:b.type==='list'?<ul key={i}>{b.items.map((t,j)=><li key={j}><LinkedText text={t} page={page} livePages={livePages}/></li>)}</ul>:<figure key={i}><Photo page={page} asset={page.media.find(a=>a.id===b.assetId)}/><figcaption>Temos iliustracija</figcaption></figure>)}
const navItems=[['gidai','Pasirinkimo gidai'],['apie-projekta','Apie projektą'],['kontaktai','Aprašyti langą']] as const;
function Header({page,livePages}:Props){const links=navItems.map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`} aria-current={page.slug===slug?'page':undefined}>{label}{slug==='kontaktai'&&' ↗'}</a>);return <header className={s.header}><a className={s.brand} href="/" aria-label="Roletai Klaipėdoje – pradžia"><Mark/><span>Roletai<br/><strong>Klaipėdoje</strong></span></a><nav className={s.desktopNav} aria-label="Pagrindinė navigacija">{links}</nav><details className={s.mobileNav}><summary>Meniu</summary><nav aria-label="Mobilioji navigacija">{links}</nav></details></header>}
function GuideList({livePages}:Props){return <div className={s.guideList}>{livePages.filter(p=>p.type==='guide').map((p,i)=><article key={p.id}><span className={s.number}>{String(i+1).padStart(2,'0')}</span><div><h3><a href={nichePagePath(p)}>{p.title}</a></h3><p>{p.description}</p><a href={nichePagePath(p)} className={s.textLink}>Skaityti gidą <span aria-hidden="true">↗</span></a></div><a href={nichePagePath(p)} tabIndex={-1} aria-hidden="true" className={s.guidePhoto}><Photo page={p} sizes="(max-width: 600px) 120px, 240px"/></a></article>)}</div>}
function Home(props:Props){const {page,livePages}=props;return <>
 <section className={s.hero}><p className={s.eyebrow}>Langas · šviesa · kasdienybė</p><h1>{page.title}</h1><div className={s.heroCopy}><Blocks blocks={page.body.slice(0,1)} page={page} livePages={livePages}/><a className={s.button} href="/gidai">Rasti savo pasirinkimo tašką ↗</a></div><figure className={s.panorama}><Photo page={page} priority sizes="(max-width: 1200px) calc(100vw - 40px), 1160px"/><figcaption>Iliustracinis interjeras</figcaption></figure><div className={s.pilot}><Blocks blocks={page.body.slice(1,2)} page={page} livePages={livePages}/></div></section>
 <section className={s.homeContent}><div className={s.sectionLabel}><span>01 / Pasiruošimas</span><h2>Savo langą<br/> pažįstate jūs.</h2><p>Pradėkite nuo kambario, paros meto ir norimo pokyčio.</p></div><div className={s.prose}><Blocks blocks={page.body.slice(2)} offset={2} page={page} livePages={livePages}/></div></section>
 <section className={s.guides}><div className={s.sectionTitle}><div><p className={s.eyebrow}>02 / Atsakymai prieš renkantis</p><h2>Po vieną aiškų klausimą.</h2></div><a href="/gidai" className={s.textLink}>Visi gidai ↗</a></div><GuideList {...props}/></section>
 <section className={s.callout}><h2>Koks šviesos pokytis<br/>reikalingas jums?</h2><div><p>Užrašykite kambarį, langų skaičių ir tai, kas dabar trukdo.</p><a href="/kontaktai#poreikis" className={s.button}>Aprašyti savo langą ↗</a></div></section>
 </>}
function Inner(props:Props){const {page,pkg,livePages}=props,guide=page.type==='guide',index=page.slug==='gidai';const toc=page.body.flatMap((b,i)=>b.type==='heading'&&b.level===2?[{text:b.text,id:`section-${i}`}]:[]);return <>
 <section className={s.pageIntro}><nav className={s.crumbs} aria-label="Puslapio kelias">{nicheBreadcrumbs(pkg,page,livePages).map((b:{path:string;name:string},i:number,a:unknown[])=><span key={b.path}>{i>0&&<span aria-hidden="true"> / </span>}{i===a.length-1?<span aria-current="page">{b.name}</span>:<a href={b.path}>{b.name}</a>}</span>)}</nav><p className={s.eyebrow}>{guide?'Pasirinkimo gidas':'Roletai Klaipėdoje'}</p><h1>{page.title}</h1><p className={s.description}>{page.description}</p>{guide&&<ArticleMeta pkg={pkg} page={page} pages={livePages} className={s.byline}/>}</section>
 {index?<section className={s.index}><div className={s.prose}><Blocks blocks={page.body} page={page} livePages={livePages}/></div><GuideList {...props}/></section>:<div className={`${s.readingLayout} ${guide?s.guideLayout:''}`}>{guide&&<aside className={s.contents}><details open><summary>Šiame gide</summary><nav aria-label="Gido turinys">{toc.map(t=><a key={t.id} href={`#${t.id}`}>{t.text}</a>)}{!!page.externalLinks?.length&&<a href="#saltiniai">Šaltiniai</a>}</nav></details><a href="/kontaktai#poreikis" className={s.textLink}>Aprašyti savo langą ↗</a></aside>}<article className={s.prose}>{guide&&<figure className={s.articlePhoto}><Photo page={page} priority/><figcaption>Temos iliustracija</figcaption></figure>}<Blocks blocks={page.body} page={page} livePages={livePages}/>{!!page.externalLinks?.length&&<section id="saltiniai" className={s.sources}><h2>Šaltiniai ir jų taikymo ribos</h2><ul>{page.externalLinks.map(l=><li key={l.url}><a href={l.url}>{l.label}</a><p>{l.reason}</p></li>)}</ul></section>}</article></div>}
 {page.slug==='kontaktai'&&<WindowInquiry/>}{page.links.length>0&&!index&&<section className={s.related}><h2>Kitas jūsų žingsnis</h2>{page.links.map(l=>{const p=livePages.find(p=>p.id===l.targetPageId);return p?<a key={p.id} href={nichePagePath(p)}>{l.label} ↗</a>:null})}</section>}
 </>}
function Footer({pkg,livePages}:Props){return <footer className={s.footer}><div className={s.footerTop}><div><a href="/" className={s.brand}><Mark/><span>Roletai<br/><strong>Klaipėdoje</strong></span></a><p>MB Pinet<br/><a href={`mailto:${pkg.site.contact.email}`}>{pkg.site.contact.email}</a></p></div><nav aria-label="Poraštės navigacija">{[['gidai','Gidai'],['kontaktai','Kontaktai'],['apie-projekta','Apie projektą'],['redakcija','Redakcija ir pataisymai'],['privatumas','Privatumas'],['naudojimo-salygos','Naudojimo sąlygos']].map(([slug,label])=>livePages.some(p=>p.slug===slug)&&<a key={slug} href={`/${slug}`}>{label}</a>)}</nav></div><div className={s.footerBottom}><p>{pkg.site.offer}</p><p>Mūsų verslas automatizuotas su <a href="https://verslomatika.lt/">verslomatika.lt</a></p></div></footer>}
export function RoletaiklaipedojeSite(props:Props){return <div className={s.shell}><InterestTracking/><a className={s.skip} href="#turinys">Pereiti prie turinio</a><script type="application/ld+json" dangerouslySetInnerHTML={{__html:nicheJsonLd(props.pkg,props.page)}}/><Header {...props}/><main id="turinys" tabIndex={-1}>{props.page.type==='home'?<Home {...props}/>:<Inner {...props}/>}</main><Footer {...props}/></div>}
