import type { ArticleRecord } from "./content";

/** Curated file-backed articles. Fixed timestamps allow a runtime reveal without a new deploy. */
export const NEW_ARTICLES: ArticleRecord[] = [
  {
    id: "lt-christmas-hub-2026",
    siteId: "dovanos123",
    locale: "lt-LT",
    slug: "kalediniu-dovanu-gidas-2026",
    title: "Kalėdinių dovanų gidas 2026: kaip išrinkti pagal žmogų, o ne reklamą",
    excerpt: "Aiški Kalėdų dovanų atrankos sistema: nuo gavėjo pomėgių ir biudžeto iki įteikimo laiko, su konkrečiomis idėjomis porai, šeimai ir draugams.",
    category: "Kalėdinės dovanos",
    publishAt: "2026-09-23T07:30:00+03:00",
    publicationState: "published",
    readingMinutes: 7,
    relatedIds: ["lt-christmas-couple", "lt-christmas-man", "lt-gift-planning-2026", "lt-gifts-under-20-2026"],
    authorIds: ["dovanos123-redakcija"],
    sourceIds: ["source-memorycasting"],
    productRecommendation: true,
    featuredImage: {
      src: "/images/articles/kalediniu-dovanu-gidas-2026.webp",
      alt: "Keli apgalvotai supakuoti kalėdiniai siuntiniai ant medinio stalo",
      width: 1536,
      height: 1024,
      credit: "AI sugeneruota redakcinė iliustracija; ne konkrečios prekės",
    },
    body: [
      "Geriausia kalėdinė dovana nėra ta, kuri šiemet dažniausiai rodoma reklamose. Pradėkite nuo trijų klausimų: ką žmogus mėgsta veikti, ko jam šiuo metu trūksta ir kiek laiko jis norės skirti pačiai dovanai? Tada nuspręskite, ar labiau tiks daiktas, patirtis, ar asmeniškas prisiminimas. Šis gidas padės tą sprendimą priimti be begalinio atsitiktinių prekių sąrašo.",
      "Prieš atsidarydami parduotuvę, viename lape užrašykite gavėją, biudžetą, pristatymo arba paruošimo terminą ir vieną sakinį „šį žmogų nudžiugintų, nes…“. Jei sakinio neužbaigiate, dovanos dar nesirinkite — trūksta informacijos apie žmogų, ne apie prekes.",
      "## Greita atrankos matrica",
      "• Jei žmogus aiškiai įvardijo konkretų poreikį, rinkitės tikslų, suderinamą ir grąžinamą daiktą. Dydžiai, modeliai ir hobio įranga be tikslių duomenų yra rizikingi.",
      "• Jei jis vertina bendrą laiką, siūlykite patirtį su realiai įmanoma data. Bilietas be laisvo savaitgalio gali tapti pareiga, ne dovana.",
      "• Jei svarbi bendra istorija, rinkitės nuotraukų albumą, asmeninį laišką ar kartu sukuriamą objektą. Sentimentali dovana veikia tik tada, kai ji atitinka gavėjo skonį.",
      "• Jei žmogaus gerai nepažįstate, saugiau rinktis mažą kokybišką sunaudojamą dovaną arba lankstų kuponą, o ne intymų suvenyrą.",
      "## Ką dovanoti skirtingiems žmonėms?",
      "### Porai",
      "Pagalvokite apie abu, ne vieną iš jų. Bendras vakaras, žaidimas, kurį jie tikrai žaistų, arba kurį kartu sukurtų, geriau už vieną dekoratyvinį daiktą. Rankų liejimo rinkinys gali tikti porai, kuriai patinka ramūs kūrybiniai užsiėmimai ir norisi apčiuopiamo prisiminimo. Jei abu nemėgsta rankdarbių, dovanokite kitokią patirtį. Išsamesnius pasirinkimo kriterijus rasite susijusiame kalėdinių dovanų porai gide.",
      "### Vyrui, kuris turi konkretų pomėgį",
      "Dovaną siekite su jo realia rutina. Dviratininkui dažniau praverčia mažas geras aksesuaras nei nežinomo dydžio apranga. Kavos mėgėjui — išbandyti naują skonį, o ne dubliuoti turimą aparatą. Jei abejojate dėl suderinamumo, paklauskite artimo žmogaus arba rinkitės čekį. Plačiau apie atranką pagal pomėgius rašome gide vyrui.",
      "### Tėvams ir šeimai",
      "Šeimai gerai tinka dovana, kurią galima naudoti kartu: namų žaidimas, bendro patiekalo ingredientų rinkinys, fotografijų knyga ar suplanuota išvyka. Prieš pirkdami šeimai skirtą kūrybinį rinkinį patikrinkite, kiek žmonių realiai gali dalyvauti ir ar mažiems vaikams jis tinka pagal gamintojo instrukciją. Saugumo teiginių vien iš reklamos nepriimkite kaip garantijos.",
      "### Draugui ar kolegai",
      "Rinkitės mažesnį įsipareigojimą: konkretaus pomėgio smulkmeną, mėgstamą skanėstą ar kuponą ten, kur žmogus iš tiesų lankosi. Kolegai venkite pernelyg asmeninių, kvapnių ar sveikatą komentuojančių dovanų. Trumpas paaiškinimas ant atviruko dažnai suteikia daugiau vertės nei brangesnė pakuotė.",
      "## Biudžetas: pirmiau riba, tada idėja",
      "Bendrą sumą padalykite gavėjams dar prieš ieškodami prekių. Prie kiekvienos dovanos pridėkite galimas pakavimo ir pristatymo išlaidas. Mažam biudžetui tinka viena prasminga nuotrauka rėmelyje, ranka parašytas laiškas su žmogaus mėgstamu gėrimu ar apgalvotas valgis kartu. Jei biudžetas iki 20 €, nesistenkite imituoti prabangios dovanos — rinkitės vieną tikslų gestą.",
      "Didesnė suma savaime nepadaro dovanos tinkamesnės. Brangesnį rinkinį ar patirtį svarstykite tada, kai žinote, kad gavėjas turės laiko ir noro ja pasinaudoti. Rankų liejimo rinkinys nėra biudžetinė smulkmena; jį vertinkite kaip bendros veiklos ir būsimo prisiminimo dovaną, o aktualią komplektaciją bei kainą tikrinkite pardavėjo puslapyje.",
      "## Kada pradėti?",
      "Rugsėjį ir spalį pakanka susidaryti žmonių bei idėjų sąrašą. Lapkritį verta tikrinti personalizuotų dovanų gamybos laiką, grąžinimo sąlygas ir atsarginį variantą. Gruodį nepasikliaukite bendru pažadu „greitas pristatymas“: prieš apmokėdami peržiūrėkite konkretaus pardavėjo terminą savo miestui ir užsakymo dienai. Šiame gide sąmoningai nerašome nekintančių „paskutinės užsakymo dienos“ datų, nes jos kinta.",
      "## Ko geriau vengti",
      "• Dovanos, kuri iš pirmo žvilgsnio atrodo įspūdinga, bet reikalauja brangių papildomų pirkinių.",
      "• Drabužių ar įrangos be tikslaus dydžio, modelio arba grąžinimo galimybės.",
      "• Įsipareigojimo patirčiai, kurios laiko gavėjas negalės pasirinkti.",
      "• Vaikams ar kūdikiams skirtų priemonių, kurių amžiaus ir naudojimo instrukcijos nepatikrinote.",
      "• Vien tik nuolaidos skatinamo pirkinio: nuolaida nėra priežastis, kodėl dovana tinka.",
      "## Trumpas galutinis patikrinimas",
      "Paklauskite savęs: ar galiu paaiškinti, kodėl ši dovana skirta būtent jam? Ar dovana telpa į visą, ne tik prekės, biudžetą? Ar ji bus panaudota? Ar žinau, kada ir kaip ją įteiksiu? Jei į visus keturis klausimus atsakymas aiškus, pasirinkimas greičiausiai pakankamai geras — net jei jis paprastas.",
    ],
  },
  {
    id: "lt-gift-planning-2026",
    siteId: "dovanos123",
    locale: "lt-LT",
    slug: "kaip-suplanuoti-kaledines-dovanas",
    title: "Kaip suplanuoti kalėdines dovanas be streso: 30 minučių metodas",
    excerpt: "Praktiškas planavimo lapas ir sprendimų seka: gavėjai, biudžetas, idėjos, terminai bei atsarginis variantas be spontaniškų pirkinių.",
    category: "Dovanų planavimas",
    publishAt: "2026-09-24T07:30:00+03:00",
    publicationState: "scheduled",
    readingMinutes: 6,
    relatedIds: ["lt-christmas-hub-2026", "lt-gifts-under-20-2026", "lt-christmas-couple"],
    authorIds: ["dovanos123-redakcija"],
    sourceIds: [],
    productRecommendation: false,
    featuredImage: {
      src: "/images/articles/kaip-planuoti-dovanas.webp",
      alt: "Ant stalo išdėliotos tuščios dovanų planavimo kortelės ir užrašinė",
      width: 1536,
      height: 1024,
      credit: "AI sugeneruota redakcinė iliustracija",
    },
    body: [
      "Kalėdinių dovanų planui užtenka pusvalandžio, jei nepradedate nuo parduotuvių. Pirmiausia surašykite žmones, bendrą sumą ir paskutinę dieną, kada realiai galite nupirkti arba pagaminti dovanas. Tada kiekvienam žmogui pasiūlykite dvi idėjas: vieną pagrindinę ir vieną atsarginę. Tik po to tikrinkite prekes bei kainas.",
      "Šis metodas skirtas ne „tobulam sąrašui“, o tam, kad gruodį nereikėtų pirkti pirmo daikto, kurį parodė reklama. Imkite vieną lapą arba skaičiuoklę su stulpeliais: gavėjas, pastebėjimas apie jį, idėja A, idėja B, visa suma, užsakymo data, būsena.",
      "## 1 žingsnis: atskirkite žmones nuo progų",
      "Užrašykite visus, kuriems tikrai planuojate dovanoti. Prie kiekvieno žmogaus pridėkite vieną realų pastebėjimą: „sekmadieniais kepa duoną“, „renka nuotraukas“, „nori daugiau laiko kartu“. Nerašykite abstraktaus „mėgsta gražius daiktus“ — toks apibūdinimas nepadeda rinktis.",
      "Jei nieko nežinote apie kolegą ar tolimesnį giminaitį, nekurkite tariamai asmeniškos dovanos. Pirmiau pasiteiraukite jo pomėgių arba rinkitės neutralesnį suvartojamą dalyką ir pridėkite nuoširdų sveikinimą.",
      "## 2 žingsnis: suskaičiuokite visą, o ne vien prekių biudžetą",
      "Tarkime, turite 120 € šešioms dovanoms. Tai nereiškia, kad kiekvienai prekei turite po 20 €. Palikite dalį pakavimui, siuntimui ir vienam nenumatytam pakeitimui. Pavyzdžiui, jei šiems dalykams rezervuojate 15 €, prekėms lieka 105 €. Toliau paskirstykite pagal santykį ir pasirinkimą, o ne matematiškai po lygiai.",
      "Biudžeto riba turi būti matoma prieš perkant. Kai randate patrauklią prekę, pridėkite pristatymą, papildomas dalis ir pakuotę. Jei visuma viršija ribą, nekeiskite viso plano dėl vienos nuolaidos — ieškokite kito varianto.",
      "## 3 žingsnis: kiekvienam žmogui palikite du pasirinkimus",
      "Pagrindinė idėja turi būti konkreti: „13×18 cm rėmelis su mūsų kelionės nuotrauka“ yra geriau nei „kažkas sentimentalaus“. Atsarginė idėja turi būti nepriklausoma nuo pirmosios, pavyzdžiui, bendra vakarienė namuose arba knygyno kuponas. Taip vienam pirkiniui dingus iš prekybos planas nesugriūva.",
      "Vertinkite abi idėjas trimis balais nuo 0 iki 2: tinkamumas žmogui, tikimybė naudoti ir pasiruošimo paprastumas. Pavyzdžiui, patirtis gali puikiai tikti, bet jei reikia suderinti keturias užimtas dienotvarkes, jos įgyvendinimo balas mažas. Mažiau įspūdinga, bet tikrai įvykstanti dovana dažnai yra geresnė.",
      "## 4 žingsnis: sudarykite terminų eilę",
      "Pirmiau spręskite dovanas, kurias reikia pagaminti, personalizuoti arba išsiųsti į kitą miestą. Po jų — lengvai grąžinamus daiktus, galiausiai — vietoje nupirktus ar pačių paruoštus gestus. Pardavėjų terminus tikrinkite konkrečią pirkimo dieną. Šiame gide nepateikiame tariamai universalių kurjerių datų.",
      "Užrašykite ne vien „nupirkti“, bet ir „gauta“, „patikrinta“, „supakuota“. Kai dovana atvyksta, patikrinkite jos būklę ir komplektaciją; paskutinę dieną tai gali būti per vėlu.",
      "## 5 žingsnis: suplanuokite įteikimą",
      "Dovana nebaigta, kol nežinote, kaip ją įteiksite. Bendrai patirčiai pridėkite siūlomą datą arba bent aiškų būdą ją susiderinti. Kūrybiniam rinkiniui numatykite laisvą vakarą ir erdvę darbui. Mažą simbolinį daiktą papildykite vienu sakiniu, kodėl jį pasirinkote. Tai nebrangu, bet padeda dovanai turėti kontekstą.",
      "## Trys pavyzdžiai, kaip tai atrodo praktiškai",
      "• Partneriui, kuris mėgsta bendrą laiką: pagrindinė idėja — namuose atliekamas kūrybinis projektas; atsarginė — suplanuotas pasimatymas. Jei rankdarbių nemėgsta, pagrindinę idėją atmeskite.",
      "• Tėčiui, kuris nuolat gamina: pagrindinė — tikslus, jo virtuvei tinkantis priedas; atsarginė — jo mėgstamo patiekalo vakarienė kartu. Prieš perkant įrankį patikrinkite, ar jo jau neturi.",
      "• Kolegei, kurios pomėgių nežinote: pagrindinė — neutralus nedidelis arbatos rinkinys; atsarginė — dovanų kuponas. Venkite asmeninio skonio ar sveikatos užuominų.",
      "## Kontrolinis sąrašas prieš gruodį",
      "• Visi gavėjai įtraukti, nė vienas neatsirado vien iš kaltės jausmo.",
      "• Kiekvienai dovanai yra bendra suma ir atsarginė idėja.",
      "• Personalizuojamiems pirkiniams patikrintas gamybos laikas.",
      "• Gavėjas turi realią galimybę patirtimi pasinaudoti.",
      "• Siuntimo ir pakavimo išlaidos telpa į bendrą ribą.",
      "Jei dovanų sąrašas vis dar kelia stresą, sumažinkite pasirinkimų skaičių. Vienam žmogui reikia ne dešimties kandidatų, o vieno pagrįsto sprendimo ir atsarginio plano.",
    ],
  },
  {
    id: "lt-gifts-under-20-2026",
    siteId: "dovanos123",
    locale: "lt-LT",
    slug: "kaledines-dovanos-iki-20-euru",
    title: "Kalėdinės dovanos iki 20 €: 7 idėjos, kurios neatrodo atsitiktinės",
    excerpt: "Septynios mažo biudžeto idėjos su pasirinkimo kriterijais, konkrečiais Lietuvos parduotuvių pavyzdžiais ir priminimu patikrinti kainą bei pristatymą.",
    category: "Dovanos pagal biudžetą",
    publishAt: "2026-09-25T07:30:00+03:00",
    publicationState: "scheduled",
    readingMinutes: 7,
    relatedIds: ["lt-christmas-hub-2026", "lt-gift-planning-2026", "lt-christmas-couple"],
    authorIds: ["dovanos123-redakcija"],
    sourceIds: ["source-ikea-frame", "source-ikea-mug", "source-skonis-dovanos", "source-pegasas-kuponas"],
    productRecommendation: false,
    featuredImage: {
      src: "/images/articles/dovanos-iki-20-euru.webp",
      alt: "Nedidelės dovanos idėjos: puodelis, rėmelis ir žvakė ant stalo",
      width: 1536,
      height: 1024,
      credit: "AI sugeneruota idėjų iliustracija; ne žemiau minimų prekių nuotrauka",
    },
    body: [
      "Iki 20 € galima išrinkti gerą kalėdinę dovaną, jei renkatės vieną aiškią mintį, o ne atsitiktinių smulkmenų rinkinį. Pradėkite nuo žmogaus įpročio: rytinė arbata, mėgstama nuotrauka, bendras žaidimas ar norima knyga. Tada patikrinkite, ar visa dovana — prekė, pakavimas ir pristatymas — telpa į 20 €. Žemiau pateikti konkretūs pavyzdžiai yra orientyrai, ne pažadas, kad kaina ar likutis nesikeis.",
      "Parduotuvių puslapius peržiūrėjome 2026-09-23. Jei straipsnį skaitote vėliau, prieš pirkdami pasitikrinkite aktualią kainą, prekės likutį, pristatymo mokestį ir grąžinimo taisykles. Nuorodos nėra mokamos partnerių nuorodos. Memory Casting rinkinys į šį biudžetą nepatenka, todėl jo čia nerekomenduojame.",
      "## 1. Nuotrauka rėmelyje su vienu sakiniu",
      "Tinka tėvams, seneliams ar artimam draugui, jei turite kadrą, kuris jiems tikrai ką nors reiškia. Pirkite rėmelį pagal nuotraukos dydį, o ne vien interjero spalvą. Kaip konkretų pasirinkimo pavyzdį galite apžiūrėti [[13×18 cm RÖDALM rėmelį|https://www.ikea.com/lt/lt/p/roedalm-remelis-berzo-rastas-30548866/]]. Peržiūros metu jo kaina buvo 2,99 €, tačiau nuotraukos spauda, siuntimas ir pakuotė kainuos papildomai.",
      "Netinka, jei neturite leidimo naudoti privačią kito žmogaus nuotrauką arba nežinote, ar gavėjas nori asmenines nuotraukas laikyti matomoje vietoje. Tokiu atveju rinkitės albumą ar skaitmeninį pasidalijimą.",
      "## 2. Puodelis ir žmogaus mėgstamas gėrimas",
      "Pats puodelis nėra originali dovana; konkretus rytinis ritualas ją gali padaryti asmenišką. Rinkitės talpą, kuri atitinka žmogaus įprotį, ir pridėkite nedidelį jo mėgstamos arbatos ar kavos kiekį. [[DINERA puodelis|https://www.ikea.com/lt/lt/p/dinera-puodelis-art-60350646/]] yra vienas paprasto indo pavyzdys; peržiūros metu kaina buvo 1,99 €. Patikrinkite, ar gavėjas neturi pilnos spintelės puodelių — jei turi, geriau dovanokite vien mėgstamą gėrimą.",
      "## 3. Nedidelis arbatos ar kavos rinkinys",
      "Tinka žmogui, kuris mėgsta ragauti naujus skonius. Pirmiausia sužinokite, ar jis geria kavą, ar arbatą, ar vengia kofeino. [[„Skonis ir kvapas“ dovanų skyriuje|https://www.skonis-kvapas.lt/dovanos]] galite palyginti rinkinių sudėtį ir aktualias kainas. Į 20 € ribą įtraukite ir pristatymą. Nežinant mitybos ribojimų saugiau rinktis ne maisto produktą arba paklausti.",
      "## 4. Mažas namų vakaras vietoj daikto",
      "Pakvieskite žmogų vakarienei, pasivaikščiojimui su karštu gėrimu arba bendram mėgstamo filmo vakarui. Prie dovanos pridėkite kortelę su dviem galimomis datomis, kad pažadas netaptų miglotas. Ši idėja ypač gerai veikia porai ar draugui, kuriam svarbus laikas kartu; netinka, jei žmogui nepatogu derinti planus.",
      "## 5. Konkrečios knygos kuponas arba skaitymo pasirinkimas",
      "Jei žinote, kad žmogus skaito, bet nežinote jo norimos knygos, leiskite išsirinkti pačiam. [[„Pegaso“ elektroninis kuponas|https://www.pegasas.lt/dovanu-kuponai/el-dovanu-kuponas-21001319/]] yra vienas pasirinkimo pavyzdys; prieš perkant patikrinkite, kokie nominalai siūlomi dabar ir kokios naudojimo bei galiojimo sąlygos. Įteikdami parašykite, kokį žanrą ar autorių prisiminėte — taip kuponas netampa beasmenis.",
      "## 6. Asmeninis receptas ir jo ingredientai",
      "Jei turite bendrą patiekalo prisiminimą, ranka užrašykite receptą ir supakuokite kelis ilgiau išsilaikančius ingredientus. Nežinant alergijų ar mitybos įpročių maisto nedovanokite aklai. Į bendrą sumą įtraukite ir tarą, o greitai gendančius produktus pirkite tik prieš įteikimą.",
      "## 7. Mažas pomėgio papildymas",
      "Knygų mėgėjui gali tikti kokybiškas skirtukas, sodininkui — sėklos ar mažas įrankis, piešiančiam — specifinis popierius. Tačiau tik tada, kai žinote tikslų pomėgį ir neturimą priedą. Profesionalui mėgėjiškas rinkinys dažnai nereikalingas; tokiu atveju geriau klausti arba rinktis kitą idėją.",
      "## Kaip palyginti kandidatų vertę",
      "Kiekvienai idėjai skirkite po balą už tris dalykus: ar ji atitinka žmogaus įprotį, ar ją tikrai panaudos, ar įteikimas įmanomas laiku. Jei dovana graži, bet žmogus jos nenaudos, pakeiskite ją. 20 € riba nėra tikslas, kurį privalote išleisti iki paskutinio cento; 5 € dovana su prasme gali būti geresnė už skubotą 19,99 € pirkinį.",
      "Pristatymas mažoms dovanoms gali sudaryti didelę sumos dalį. Todėl rinkitės atsiėmimą, kai tai patogu, arba sujunkite pirkinius vienoje vietoje tik jei jų tikrai reikia. Neužsisakykite papildomo daikto vien tam, kad pasiektumėte nemokamo pristatymo ribą.",
      "## Trumpi atsakymai",
      "### Ar kuponas per daug beasmenis?",
      "Ne, jei jis susijęs su žinomu žmogaus pomėgiu ir papildytas konkrečiu palinkėjimu. Jei net neįsivaizduojate, kur žmogus jį panaudos, kuponas nepadeda.",
      "### Ar galima dovanoti pačių pagamintą daiktą?",
      "Taip, jei jis tvarkingas, naudingas arba turi jums abiem suprantamą istoriją. Vien pastangų faktas nereiškia, kad gavėjas norės daiktą laikyti namuose.",
      "### Kas, jei 20 € neužtenka norimai dovanai?",
      "Neslėpkite papildomų išlaidų. Keiskite idėją, dovanokite bendrą laiką arba, jei santykis tinkamas, susitarkite dėl bendros dovanos su kitu žmogumi. Neskolinkitės vien dėl šventinio įspūdžio.",
    ],
  },
];
