-- First private-pilot content batch. Replace or edit through the ingest API
-- after real editorial review. INSERT OR IGNORE keeps deploys idempotent.
INSERT OR IGNORE INTO articles (id, site_id, locale, translation_group_id, external_id, slug, title, excerpt, category, blocks_json, publication_state, publish_at, published_version_id, author_ids_json, source_ids_json, created_at, updated_at)
VALUES ('article-lt-first-001', 'dovanos123', 'lt-LT', 'gift-casting-001', 'lt-hand-casting-guide-001', 'ranku-liejimo-rinkinys-kaip-pasiruosti', 'Rankų liejimo rinkinys: kaip pasiruošti pirmajam liejiniui', 'Praktinis gidas poroms: ką pasiruošti prieš rankų liejimą, kaip išvengti dažniausių klaidų ir ko tikėtis iš galutinio rezultato.', 'Personalizuotos dovanos', '[{"type":"paragraph","text":"Rankų liejimo rinkinys yra bendra patirtis, todėl geriausias rezultatas prasideda nuo ramaus pasiruošimo, o ne nuo skubėjimo."},{"type":"heading","level":2,"text":"Ką pasiruošti prieš pradedant"},{"type":"paragraph","text":"Pasirinkite stabilų stalą, pasiruoškite indą mišiniui, rankšluostį ir laikmatį. Prieš maišydami perskaitykite visą rinkinio instrukciją."},{"type":"heading","level":2,"text":"Kaip išvengti dažniausių klaidų"},{"type":"list","ordered":false,"items":["Neskubėkite maišydami formavimo mišinį.","Rankas laikykite ramiai visą nurodytą laiką.","Prieš išimdami liejinį palaukite, kol medžiaga sukietės."]},{"type":"product_cta","productId":"hand-casting-kit","label":"Peržiūrėti rankų liejimo rinkinį"}]', 'published', strftime('%s','2026-09-18 18:00:00') * 1000, 'version-lt-first-001', '["aiste-redaktore"]', '["source-hand-casting"]', unixepoch('now') * 1000, unixepoch('now') * 1000);
INSERT OR IGNORE INTO article_versions (id, article_id, version_number, content_snapshot_json, seo_snapshot_json, schema_snapshot_json, ai_metadata_json, review_metadata_json, created_at, updated_at)
VALUES ('version-lt-first-001', 'article-lt-first-001', 1, '[{"type":"paragraph","text":"Rankų liejimo rinkinys yra bendra patirtis, todėl geriausias rezultatas prasideda nuo ramaus pasiruošimo, o ne nuo skubėjimo."}]', '{"title":"Rankų liejimo rinkinys: kaip pasiruošti pirmajam liejiniui"}', '{}', '{"source":"codex-private-pilot"}', '{"status":"private-pilot-review-required"}', unixepoch('now') * 1000, unixepoch('now') * 1000);

INSERT OR IGNORE INTO articles (id, site_id, locale, translation_group_id, external_id, slug, title, excerpt, category, blocks_json, publication_state, publish_at, published_version_id, author_ids_json, source_ids_json, created_at, updated_at)
VALUES ('article-lt-first-002', 'dovanos123', 'lt-LT', 'gift-couple-002', 'lt-gifts-for-couple-002', 'prasmingos-dovanos-porai-pagal-biudzeta', '9 prasmingos dovanos porai pagal biudžetą', 'Dovanų porai idėjos nuo mažo gesto iki bendros patirties: palyginame kainą, pasiruošimo laiką ir emocinę vertę.', 'Dovanos porai', '[{"type":"paragraph","text":"Gera dovana porai atsižvelgia į jų bendrą istoriją, o ne tik į progą kalendoriuje."},{"type":"heading","level":2,"text":"Iki 30 eurų"},{"type":"paragraph","text":"Mažesnio biudžeto dovana gali būti asmeniška: laiškas, bendra vakarienė namuose ar nedidelis daiktas su prasme."},{"type":"heading","level":2,"text":"Kai norisi bendros patirties"},{"type":"paragraph","text":"Rankų liejimo rinkinys leidžia dovaną sukurti kartu, todėl jo vertė yra ne tik galutiniame objekte, bet ir pačiame procese."}]', 'scheduled', strftime('%s','2026-09-19 04:00:00') * 1000, NULL, '["aiste-redaktore"]', '["source-gift-choice"]', unixepoch('now') * 1000, unixepoch('now') * 1000);
INSERT OR IGNORE INTO article_versions (id, article_id, version_number, content_snapshot_json, seo_snapshot_json, schema_snapshot_json, ai_metadata_json, review_metadata_json, created_at, updated_at)
VALUES ('version-lt-first-002', 'article-lt-first-002', 1, '[{"type":"paragraph","text":"Gera dovana porai atsižvelgia į jų bendrą istoriją, o ne tik į progą kalendoriuje."}]', '{"title":"9 prasmingos dovanos porai pagal biudžetą"}', '{}', '{"source":"codex-private-pilot"}', '{"status":"scheduled-review-required"}', unixepoch('now') * 1000, unixepoch('now') * 1000);
INSERT OR IGNORE INTO publish_jobs (id, article_id, version_id, due_at, status, lease_until, attempts, last_error, created_at, updated_at)
VALUES ('job-lt-first-002', 'article-lt-first-002', 'version-lt-first-002', strftime('%s','2026-09-19 04:00:00') * 1000, 'pending', NULL, 0, NULL, unixepoch('now') * 1000, unixepoch('now') * 1000);

INSERT OR IGNORE INTO articles (id, site_id, locale, translation_group_id, external_id, slug, title, excerpt, category, blocks_json, publication_state, publish_at, published_version_id, author_ids_json, source_ids_json, created_at, updated_at)
VALUES ('article-lt-first-003', 'dovanos123', 'lt-LT', 'gift-anniversary-003', 'lt-anniversary-ideas-003', 'ka-dovanoti-vestuviu-metiniu-proga', 'Ką dovanoti vestuvių metinių proga? Atrankos kriterijai', 'Kaip išrinkti vestuvių metinių dovaną, kuri būtų asmeniška, praktiška ir atitiktų poros kasdienybę.', 'Dovanos progai', '[{"type":"paragraph","text":"Vestuvių metinių proga verta pradėti nuo poros įpročių, bendrų prisiminimų ir to, ką jie iš tikrųjų mėgsta veikti kartu."},{"type":"heading","level":2,"text":"Trys klausimai prieš renkant dovaną"},{"type":"list","ordered":true,"items":["Ar dovana sukuria bendrą momentą?","Ar ją bus patogu naudoti arba eksponuoti?","Ar ji atitinka šios poros istoriją?"]}]', 'review', NULL, NULL, '["aiste-redaktore"]', '["source-gift-choice"]', unixepoch('now') * 1000, unixepoch('now') * 1000);
INSERT OR IGNORE INTO article_versions (id, article_id, version_number, content_snapshot_json, seo_snapshot_json, schema_snapshot_json, ai_metadata_json, review_metadata_json, created_at, updated_at)
VALUES ('version-lt-first-003', 'article-lt-first-003', 1, '[{"type":"paragraph","text":"Vestuvių metinių proga verta pradėti nuo poros įpročių, bendrų prisiminimų ir to, ką jie iš tikrųjų mėgsta veikti kartu."}]', '{"title":"Ką dovanoti vestuvių metinių proga? Atrankos kriterijai"}', '{}', '{"source":"codex-private-pilot"}', '{"status":"human-review-required"}', unixepoch('now') * 1000, unixepoch('now') * 1000);
