import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
const pkg=JSON.parse(await readFile(new URL('content-package.json',import.meta.url),'utf8'));
const origin=process.argv[2]||'https://dovanos123-preview.phonebridger-app.workers.dev',production=origin==='https://dovanos123.lt';
assert.ok(production||origin==='https://dovanos123-preview.phonebridger-app.workers.dev','Own release host required');
const get=async path=>{const r=await fetch(origin+path,{redirect:'manual'});return {status:r.status,headers:r.headers,bytes:Buffer.from(await r.arrayBuffer())};};
const checks={origin,at:new Date().toISOString(),production,pages:[],media:[],boundaries:[],discovery:[]};
for(const page of pkg.pages){const path='/'+page.slug,r=await get(path),html=r.bytes.toString();assert.equal(r.status,200,path);assert.ok(html.includes(page.title.replaceAll('&','&amp;')),path+' title');assert.equal((html.match(/<h1(?:\s|>)/g)||[]).length,1,path+' one heading');assert.ok(html.includes(`rel="canonical" href="${`https://${pkg.canonicalHost}/${page.slug}`}"`),path+' canonical');
 const schemas=[...html.matchAll(/<script[^>]+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)].map(m=>JSON.parse(m[1]));assert.ok(schemas.length,path+' schema');
 if(!production)assert.match(r.headers.get('x-robots-tag'),/noindex/);else assert.ok(!/noindex/.test(r.headers.get('x-robots-tag')||''),path+' indexable');
 checks.pages.push({path,status:200,canonical:`https://${pkg.canonicalHost}/${page.slug}`,schema:true});
 if(page.slug===''){const urls=new Set([...html.matchAll(/(?:href|src)="([^"<>]+\.(?:css|js)(?:\?[^"<>]*)?)"/g)].map(m=>m[1]));for(const url of urls){const a=await get(url);assert.equal(a.status,200,url+' client asset');}checks.clientAssets=urls.size;}
}
const media=new Map(pkg.pages.flatMap(p=>p.media).map(m=>[m.src,m]));for(const [url,m]of media){const r=await get(url),expected=await readFile(new URL('../../content-staging/dovanos123/assets/'+url.split('/').at(-1),import.meta.url));assert.equal(r.status,200,url);assert.match(r.headers.get('content-type'),/image\/webp/);assert.equal(createHash('sha256').update(r.bytes).digest('hex'),createHash('sha256').update(expected).digest('hex'));checks.media.push({url,sha256:createHash('sha256').update(r.bytes).digest('hex')});}
for(const path of ['/niche/dovanos123/lead','/gift/dovanos123','/api/internal/publish-due','/content-assets/dovanos123/unapproved.webp','/images/legacy-private.webp','/not-a-page','/.dev.vars','/runtime/platform.sqlite']){const r=await get(path);assert.equal(r.status,404,path+' protected');checks.boundaries.push({path,status:404});}
for(const path of ['/sitemap.xml','/llms.txt','/llms-full.txt']){const r=await get(path);assert.equal(r.status,production?200:404,path);if(production){const text=r.bytes.toString();if(path==='/sitemap.xml')assert.equal((text.match(/<url>/g)||[]).length,pkg.pages.length);for(const page of pkg.pages)assert.ok(text.includes(`https://${pkg.canonicalHost}/${page.slug}`),path+' inventory '+page.id);}checks.discovery.push({path,status:r.status});}
const robots=await get('/robots.txt');assert.equal(robots.status,200);assert.ok(robots.bytes.toString().includes(production?'Sitemap: https://dovanos123.lt/sitemap.xml':'Disallow: /'));checks.robots=true;
if(production){for(const url of ['http://dovanos123.lt/kontaktai?test=1','https://www.dovanos123.lt/kontaktai?test=1']){const r=await fetch(url,{redirect:'manual'});assert.ok([301,308].includes(r.status));assert.equal(r.headers.get('location'),'https://dovanos123.lt/kontaktai?test=1');}checks.redirects=true;}
await mkdir(new URL('output/',import.meta.url),{recursive:true});await writeFile(new URL(`output/${production?'canonical':'preview'}-verification.json`,import.meta.url),JSON.stringify(checks,null,2));console.log(JSON.stringify({origin,pages:checks.pages.length,media:checks.media.length,privateMisses:checks.boundaries.length,clientAssets:checks.clientAssets,discovery:checks.discovery,pass:true}));
