import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {build} from 'esbuild';import {Miniflare} from 'miniflare';
test('actual Workers D1 queue serializes claims, retries after restart, isolates site and applies retention',async()=>{
 const directory=await mkdtemp(path.join(tmpdir(),'gift-delivery-'));let failed=true,sends=0;
 const script=(await build({stdin:{contents:"import {notifyStoredLead,maintainLeadDelivery} from './lib/niche-lead-delivery.mjs'; export default {async fetch(r,env){const input=await r.json();if(input.maintain)await maintainLeadDelivery(env,input.now);else await notifyStoredLead(env,input.id,input.now);return new Response('done');}}",resolveDir:process.cwd()},write:false,bundle:true,format:'esm',platform:'node',external:['cloudflare:*']})).outputFiles[0].text;
 const start=()=>new Miniflare({modules:true,script,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],d1Persist:directory,bindings:{RELEASE_SITE_ID:'dovanos123',LEAD_MAIL_RETRY_ENABLED:'1',MAIL_RELAY_SITE:'dovanos123',MAIL_RELAY_KEY:'b'.repeat(64),MAIL_RELAY_URL:'https://owned-mail.test/relay.php'},outboundService:async request=>{const mail=await request.json();assert.equal(mail.to,'info@pinet.lt');assert.equal(request.headers.get('x-release-site'),'dovanos123');assert.match(request.headers.get('x-release-signature'),/^[a-f0-9]{64}$/);sends++;return Response.json({accepted:!failed},{status:failed?503:200});}});
 let mf=start(),db=await mf.getD1Database('DB');const now=Date.now();
 const invoke=input=>mf.dispatchFetch('http://localhost/',{method:'POST',body:JSON.stringify(input)});
 try{
  for(const file of ['0004_niche_leads.sql','0005_niche_interest_daily.sql','0006_niche_lead_delivery.sql'])await db.exec((await readFile('drizzle/'+file,'utf8')).replace(/\n/g,' '));
  const insert=async(id,site,created)=>{await db.prepare("INSERT INTO niche_leads(id,site_id,created_at,source_path,name,email,message,consent_at,status) VALUES(?,?,?,'/kontaktai','Testas','own@example.com','Isolated test',?,'new')").bind(id,site,created,created).run();await db.prepare("INSERT INTO niche_lead_delivery(id,site_id,canonical_host,recipient) VALUES(?,?,'dovanos123.lt','info@pinet.lt')").bind(id,site).run();};
  await insert('test-one','dovanos123',now);await insert('test-other','other-site',now);
  await Promise.all([invoke({id:'test-one',now}),invoke({id:'test-one',now})]);let job=await db.prepare("SELECT * FROM niche_lead_delivery WHERE id='test-one'").first();assert.equal(sends,1);assert.equal(job.state,'pending');assert.equal(job.attempts,1);assert.ok(job.next_attempt_at>now);
  await invoke({id:'test-one',now});assert.equal(sends,1);await invoke({id:'test-other',now});assert.equal(sends,1);
  await mf.dispose();mf=start();db=await mf.getD1Database('DB');failed=false;await invoke({maintain:true,now:job.next_attempt_at+1});job=await db.prepare("SELECT * FROM niche_lead_delivery WHERE id='test-one'").first();assert.equal(job.state,'accepted');assert.equal(sends,2);assert.equal((await db.prepare("SELECT status FROM niche_leads WHERE id='test-one'").first()).status,'notified');
  await invoke({id:'test-one',now:job.next_attempt_at+1});assert.equal(sends,2);
  await insert('test-old','dovanos123',now-181*86400000);await insert('other-old','other-site',now-181*86400000);await invoke({maintain:true,now:now+86400000});assert.equal(await db.prepare("SELECT id FROM niche_leads WHERE id='test-old'").first(),null);assert.ok(await db.prepare("SELECT id FROM niche_leads WHERE id='other-old'").first());assert.equal((await db.prepare("SELECT state FROM niche_lead_delivery WHERE id='test-other'").first()).state,'pending');
 }finally{await mf.dispose();}
});
