import type { ArticleRecord } from "./content";

type ScheduledBrief = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  day: string;
  image: string;
  imageAlt: string;
  relatedIds: string[];
  body: string[];
  productRecommendation?: boolean;
};

const briefs: ScheduledBrief[] = [
  {
    id: "lt-christmas-woman-2026",
    slug: "kaledines-dovanos-moteriai",
    title: "Kalėdinės dovanos moteriai: idėjos pagal jos kasdienybę",
    excerpt: "Ne vienas sąrašas visoms: kaip pasirinkti dovaną mamai, partnerei, sesei ar kolegei pagal jų interesus ir jūsų santykį.",
    category: "Kalėdinės dovanos",
    day: "2026-09-28",
    image: "kaledines-dovanos-moteriai.webp",
    imageAlt: "Šalikas ir asmeniškas atvirukas ruošiami dovanai",
    relatedIds: ["lt-christmas-hub-2026", "lt-gifts-mother", "lt-gifts-girlfriend"],
    body: [
      "Dovanos moteriai nereikėtų rinktis vien pagal žodį „moteriai“. Mama, partnerė, sesuo ir kolegė gali turėti visiškai skirtingus pomėgius. Pirmiausia atsakykite, ką šis konkretus žmogus daro laisvalaikiu, ką jau turi ir kokios dovanos jai būtų patogu priimti.",
      "## Trijų signalų metodas",
      "Užrašykite tris pastebėtus dalykus: kokią veiklą ji pati renkasi, apie ką yra užsiminusi per pastaruosius mėnesius ir ko sąmoningai vengia. Jei ji sako norinti mažiau daiktų, dar viena dekoracija greičiausiai netiks, net jei atrodo puikiai. Jei prašo konkrečios knygos, nebandykite jos „pagerinti“ atsitiktiniu grožio rinkiniu.",
      "## Idėjos pagal santykį",
      "### Partnerei",
      "Bendrai suplanuota diena, nedidelis daiktas su jūsų istorija ar kūrybinė patirtis gali būti vertingesni už anoniminę prabangą. Jeigu svarstote [[dovaną merginai|article:lt-gifts-girlfriend]], įvertinkite, ar ji norės laiko dviese, ar atskiro daikto savo pomėgiui. Nė vieno varianto nelaikykite savaime romantiškesniu.",
      "### Mamai",
      "Paslaugą ar išvyką siūlykite tik žinodami, kad ji galės ja pasinaudoti. Jei ji mėgsta šeimos istorijas, atrinktas albumas su keliomis aiškiomis antraštėmis gali būti geras pasirinkimas. Jei ji labiau vertina praktiką, geriau išspręsti konkretų jos kasdienį nepatogumą. Plačiau — [[gidas mamai|article:lt-gifts-mother]].",
      "### Sesei ar draugei",
      "Čia padeda žinojimas, kas pasikeitė per metus: naujas būstas, pomėgis ar darbo ritmas. Venkite dovanoti tai, ką pati norėtumėte gauti. Jei dydis, skonis ar modelis neaiškus, palikite pasirinkimą gavėjai ir pridėkite asmenišką kontekstą.",
      "### Kolegei",
      "Rinkitės santūrią dovaną, atitinkančią kolektyve sutartą sumą. Stenkitės nekalbėti dovana apie išvaizdą, amžių, sveikatą ar šeimyninę padėtį. Nedidelis konkretus padėkos laiškas dažnai yra geresnė dovanos dalis už atsitiktinį suvenyrą.",
      "## Patikra prieš mokant",
      "Pridėkite siuntimo ir pakavimo išlaidas, patikrinkite grąžinimą ir terminą. Asmens duomenimis ar nuotrauka personalizuojamai dovanai gaukite tinkamą nuotrauką ir patikrinkite maketą. Jei apie gavėją žinote mažai, pirmiau paklauskite jos artimo žmogaus, o ne pirkite pagal reklamos kategoriją.",
      "Geras sprendimas paaiškinamas vienu sakiniu: „parinkau tai, nes pastebėjau, kad…“. Jei sakinio nėra, grįžkite prie žmogaus, ne prie parduotuvės filtro.",
    ],
  },
  {
    id: "lt-christmas-parents-2026",
    slug: "kaledines-dovanos-tevams",
    title: "Kalėdinės dovanos tėvams: viena bendra ar dvi atskiros?",
    excerpt: "Sprendimo būdas tėvų dovanai: kada tinka bendras laikas, kada atskiros dovanos ir kaip nepadovanoti papildomo darbo.",
    category: "Kalėdinės dovanos",
    day: "2026-09-29",
    image: "kaledines-dovanos-tevams.webp",
    imageAlt: "Rėmelyje ruošiama šeimos nuotrauka šalia dovanų",
    relatedIds: ["lt-christmas-hub-2026", "lt-gifts-mother", "lt-gifts-father", "lt-gifts-grandparents"],
    body: [
      "Tėvams dažnai perkame vieną bendrą dovaną iš patogumo. Tačiau bendra dovana gera tik tada, jei ja tikrai naudosis abu. Jei vienas mėgsta keliones, o kitas nori ramybės namuose, vienas viešbučio kuponas gali labiau įpareigoti nei nudžiuginti.",
      "## Bendros ar atskiros dovanos testas",
      "Paklauskite: ar jie patys renkasi bendrą laisvalaikį? Ar abu gali naudotis dovana be papildomų išlaidų? Ar ji nesukurs namuose darbo vienam iš jų? Jei į bent du klausimus atsakymas „ne“, verčiau paruoškite dvi mažesnes atskiras dovanas arba vieną bendrą ir po mažą asmeninį priedą.",
      "## Trys kryptys bendram pasirinkimui",
      "### Prisiminimas, kurį lengva naudoti",
      "Atrinkite 10–20 tikrai reikšmingų nuotraukų, o ne šimtus neišrūšiuotų failų. Pridėkite datas ir žmonių vardus. Rėmelis su vienu kadru tinka, kai žinote jų namų stilių ir nuotrauka nėra tokia privati, kad jos nenorėtų rodyti.",
      "### Laikas kartu su aiškiu planu",
      "Vakarienė namuose, nedidelė išvyka ar bendras žaidimo vakaras gali kainuoti mažiau nei didelis daiktas. Patirčiai įrašykite du galimus laikus ir pasisiūlykite pasirūpinti organizavimu. Nepalikite visos rezervavimo naštos tėvams.",
      "### Kūrybinis šeimos projektas",
      "Jei jie mėgsta rankdarbius ir norėtų apčiuopiamo rezultato, galima svarstyti rankų liejimo rinkinį ar kitą bendrą kūrybinį užsiėmimą. Prieš pirkdami patikrinkite dalyvių skaičių, instrukciją ir ar abu norės procese dalyvauti. Jei ne, geriau rinktis kitą patirtį.",
      "## Kada atskirti dovanas",
      "Jei mama renka knygas, o tėtis leidžia laiką dirbtuvėse, dvi konkrečios dovanos geriau už neutralų rinkinį. Pasidalykite bendrą biudžetą nebūtinai po lygiai, bet skirkite panašų dėmesį. Daugiau atrankos kriterijų pateikiame [[mamai|article:lt-gifts-mother]] ir [[tėčiui|article:lt-gifts-father]] skirtuose giduose.",
      "## Ko vengti",
      "Nedovanokite buitinio prietaiso vien todėl, kad namuose jo trūksta: tai gali būti namų išlaida, ne asmeninė dovana. Nežadėkite abonemento, kurio vėlesnius mokėjimus turės dengti tėvai. Ir nedovanokite „pagalbos“ taip abstrakčiai, kad jie turės patys jūsų prašyti — suplanuokite konkretų darbą.",
      "Galiausiai įteikite dovaną su paaiškinimu, ką pastebėjote apie jų metus. Būtent tai paverčia pasirinkimą jų, o ne bet kurių tėvų dovana.",
    ],
  },
  {
    id: "lt-christmas-family-2026",
    slug: "kaledines-dovanos-seimai",
    title: "Kalėdinės dovanos šeimai: kaip įtraukti visus, o ne tik vaikus",
    excerpt: "Bendros šeimos dovanos pagal amžių, erdvę ir laiką: žaidimai, patirtys, prisiminimai ir kūrybiniai projektai.",
    category: "Kalėdinės dovanos",
    day: "2026-09-30",
    image: "kaledines-dovanos-seimai-v2.webp",
    imageAlt: "Spalvingoje iliustracijoje šeima kartu žaidžia stalo žaidimą",
    relatedIds: ["lt-christmas-hub-2026", "lt-christmas-parents-2026", "lt-gifts-couple"],
    body: [
      "Dovana visai šeimai skiriasi nuo keturių dovanų vienoje dėžėje. Ji turi suteikti galimybę bent dalį laiko praleisti kartu. Prieš pirkdami suskaičiuokite, kas realiai dalyvaus, kokio amžiaus yra vaikai ir ar veiklai namuose pakaks vietos.",
      "## Pasirinkite pagal bendrą laiką",
      "Jei šeima turi tik trumpą vakarą, tiks veikla, kurią galima pradėti be ilgo pasiruošimo: paprastas žaidimas, vakarienės ingredientai arba nedidelė kūrybinė užduotis. Jei jie mėgsta planuoti savaitgalius, galite siūlyti išvyką, muziejų ar dirbtuves, bet iš anksto patikrinkite tinkamą amžių ir galiojimo sąlygas.",
      "## Keturi dovanų modeliai",
      "### Žaidimas, kurį žais visi",
      "Patikrinkite nurodytą žaidėjų skaičių, amžių, taisyklių sudėtingumą ir vienos partijos trukmę. Net puikus žaidimas netinka, jei jauniausias šeimos narys pusvalandį turi tik stebėti. Geriau paprastesnis, kuriame jis turi tikrą vaidmenį.",
      "### Bendra vakarienė",
      "Sukomplektuokite vieno patiekalo ingredientus ir receptą. Prieš dovanojant maistą būtina žinoti alergijas bei mitybos pasirinkimus. Jei nežinote, dovanokite kvietimą kartu gaminti ir produktus rinkitės jau susitarę.",
      "### Prisiminimų projektas",
      "Šeimos nuotraukų albumas gali sujungti skirtingas kartas, tačiau darbą atlikite jūs: atrinkite, išspausdinkite ir aprašykite nuotraukas. Kitu atveju padovanosite užduotį. Kūrybinį rinkinį rinkitės tik patikrinę jo instrukciją, reikalingą priežiūrą ir žmonių skaičių.",
      "### Patirtis už namų ribų",
      "Bilietai ar kuponas turi derėti su vaikų ritmu, kelionės trukme ir suaugusiųjų galimybėmis. Įvertinkite ir papildomas išlaidas: transportą, maistą, inventorių. Jei jų daug, dovana gali tapti neplanuota šeimos sąskaita.",
      "## Pirkimo patikra",
      "Prieš apmokėdami įsitikinkite, kad dovana tinka pagal amžių, visiems dalyviams yra vietos, o prireikus ją galima grąžinti. Jei siūlote konkrečią datą, pirmiausia pasitarkite su suaugusiaisiais. Geriausia šeimos dovana ne „tinka visiems“ etiketėje, o realiai veikia jų kalendoriuje.",
    ],
  },
  {
    id: "lt-christmas-original-2026",
    slug: "originalios-kaledines-dovanos",
    title: "Originalios Kalėdų dovanos: 6 būdai nustebinti neperkant keistenybės",
    excerpt: "Originalumas kyla iš ryšio su žmogumi. Šeši būdai sukurti netikėtą, bet naudojamą dovaną ir patikrinti jos tinkamumą.",
    category: "Kalėdinės dovanos",
    day: "2026-10-01",
    image: "originalios-kaledines-dovanos-v2.webp",
    imageAlt: "Ryškiaspalvė idėjos metafora: iš dovanų dėžės kylantys grafiniai objektai",
    relatedIds: ["lt-christmas-hub-2026", "lt-gifts-personalized", "lt-gifts-experiences"],
    body: [
      "Originali dovana nebūtinai yra negirdėtas daiktas. Staigmena gerai veikia tada, kai žmogus atpažįsta mintį: „tu mane pažįsti“. Neįprastas pirkinys be ryšio su gavėju dažniausiai tampa dar viena laikina dekoracija.",
      "## 1. Pakeiskite įteikimo scenarijų",
      "Užuot įteikę restoranų kuponą, pridėkite dviejų galimų datų planą ir pasiūlymą pasirūpinti rezervacija. Ta pati patirtis tampa konkretesnė. Jeigu gavėjui nepatinka staigūs planai, palikite datą pasirinkti jam.",
      "## 2. Susiekite du jo pomėgius",
      "Mėgstančiam skaityti ir keliauti galima paruošti maršrutą į knygoje minimą vietą arba namuose surengti teminį vakarą. Svarbu nepaversti dovanos pernelyg sudėtingu projektu, kuriam žmogus neturi laiko.",
      "## 3. Paverskite prisiminimą naudingu",
      "Vietoj užrašu apkrauto suvenyro atrinkite vieną nuotrauką ir pridėkite jai vietą: rėmelį, albumą ar nedidelį leidinį. Jei žmogus nemėgsta viešai rodyti privačių nuotraukų, pasirinkite uždaromą formatą.",
      "## 4. Padovanokite bendrą kūrimo laiką",
      "Pasirinkite užsiėmimą, kurio abu norėtumėte imtis: keramiką, maisto gaminimą, sodinimą ar rankų liejimo rinkinį. Kūrybinė dovana netinka, jei žmogui atrodytų kaip privaloma užduotis. Perskaitykite instrukciją ir sužinokite, kiek erdvės bei laiko reikės.",
      "## 5. Papildykite tiksliu paaiškinimu",
      "Ranka parašytas sakinys apie konkretų pastebėjimą gali pakeisti paprastą dovaną. „Prisiminiau, kaip po ilgos kelionės kalbėjome apie…“ yra stipriau nei universalus palinkėjimas. Jei norisi daugiau idėjų, skaitykite [[prasmingų dovanų gidą|article:lt-gifts-meaningful]].",
      "## 6. Neįpareigokite vien dėl originalumo",
      "Gyvūnai, augalai, prenumeratos ir dideli interjero daiktai sukuria priežiūros pareigą. Net jei jie netikėti, dovana neturėtų tapti problema. Pasitikrinkite, ar gavėjas gali ir nori ją priimti.",
      "Prieš pirkdami vienu sakiniu įvardykite, kuo sprendimas originalus būtent šiam žmogui, ir atskirai — kaip jis dovana pasinaudos. Jei galite atsakyti tik į pirmą dalį, idėją dar pataisykite.",
    ],
  },
  {
    id: "lt-christmas-friends-2026",
    slug: "kaledines-dovanos-draugams",
    title: "Kalėdinės dovanos draugams: idėjos be spėlionių ir įsipareigojimų",
    excerpt: "Kaip draugams išrinkti mažą, tikslų gestą pagal bendrą istoriją, pomėgius ir aiškų biudžetą.",
    category: "Kalėdinės dovanos",
    day: "2026-10-02",
    image: "kaledines-dovanos-draugams.webp",
    imageAlt: "Draugai apsikeičia nedidele dovana kavinėje prie lango",
    relatedIds: ["lt-christmas-hub-2026", "lt-gifts-female-friend", "lt-gifts-male-friend"],
    body: [
      "Draugui Kalėdoms nebūtina išleisti daug, bet reikia parodyti, kad pastebėjote, kas jam patinka. Susitarkite dėl biudžeto, jei dovanojate vieni kitiems grupėje. Taip niekas neturės jaustis įpareigotas atsilyginti brangesne dovana.",
      "## Pradėkite nuo bendro konteksto",
      "Pagalvokite apie vieną per metus kartu patirtą dalyką: žygį, pokalbį, filmą ar valgį. Dovana gali pratęsti tą istoriją. Pavyzdžiui, po bendro žygio tinka mažas, realiai naudojamas lauko priedas arba kvietimas į kitą maršrutą, bet ne atsitiktinis „nuotykių“ suvenyras.",
      "## Trys saugios kryptys",
      "### Maža naudinga detalė",
      "Rinkitės tik žinodami konkretų pomėgį ir ko draugas dar neturi. Specializuotos įrangos be modelio ar dydžio nepirkite — mėgėjai dažnai turi savus kriterijus. Geras priedas išsprendžia smulkų nepatogumą, o ne dubliuoja daiktą.",
      "### Valgomas arba sunaudojamas pasirinkimas",
      "Kava, arbata ar kitas mėgstamas produktas tinka, jei žinote mitybos ribojimus. Nekurkite didelio rinkinio vien dėl išvaizdos; viena tiksli prekė su paaiškinimu vertingesnė už penkias, kurias žmogus paliks spintelėje.",
      "### Bendra patirtis",
      "Bilietas, žaidimų vakaras ar jūsų surengta vakarienė veikia, jei draugas gali pasirinkti laiką. Palikite du variantus, o ne vieną jau nupirktą datą. Jei planas priklauso nuo kitų žmonių, prieš pirkdami pasitikrinkite jų galimybes.",
      "## Kada nedovanoti asmeniškos dovanos",
      "Jei santykis naujas arba draugas nemėgsta sentimentalių objektų, nuotrauka rėmelyje gali būti pernelyg intymi. Tokiu atveju pasirinkite praktišką smulkmeną arba drauge praleistą laiką. Daugiau niuansų rasite atskiruose [[giduose draugei|article:lt-gifts-female-friend]] ir [[draugui|article:lt-gifts-male-friend]].",
      "Prieš įteikdami patikrinkite grąžinimą, galiojimą ir visą kainą su pristatymu. Draugystei dovana turi suteikti lengvumo, ne naują užduotį.",
    ],
  },
  {
    id: "lt-gifts-boyfriend",
    slug: "dovanos-vaikinui",
    title: "Dovanos vaikinui: pasirinkite pagal tai, ką jis iš tikrųjų veikia",
    excerpt: "Praktiška atranka vaikinui pagal pomėgį, santykio etapą ir dovanos naudojimo tikimybę, be stereotipinių sąrašų.",
    category: "Dovanos pagal gavėją",
    day: "2026-10-05",
    image: "dovanos-vaikinui-v2.webp",
    imageAlt: "Pora apsikeičia maža dovana lietingame vakaro mieste",
    relatedIds: ["lt-christmas-man", "lt-gifts-girlfriend", "lt-gifts-couple"],
    body: [
      "Geriausia dovana vaikinui nebūtinai susijusi su jo lytimi. Ji susijusi su tuo, ką jis daro po darbo, apie ką kalba ir kokius planus nuolat atideda. Prieš ieškodami prekių užrašykite vieną konkretų jo įprotį ir vieną nepatogumą, kurį būtų malonu pašalinti.",
      "## Jei santykis dar naujas",
      "Nedovanokite labai brangaus daikto ar pernelyg asmeniško suvenyro, jei dar nežinote vienas kito lūkesčių. Nedidelis pomėgio priedas, bilietai į renginį, kurį abu norėtumėte aplankyti, arba suplanuotas vakaras suteikia dėmesio nesukurdamas spaudimo. Patirties datos nederėtų rezervuoti nepasitarus.",
      "## Jei vienas kitą gerai pažįstate",
      "Gali tikti daiktas, kurio tikslų modelį jis yra paminėjęs, arba bendros istorijos tęsinys. Pavyzdžiui, po kartu pradėto gaminimo pomėgio vertingiau papildyti turimą įrangą nei pirkti kitą pradinį rinkinį. Jei renkatės aprangą ar techniką, patikrinkite dydį, suderinamumą ir grąžinimo galimybę.",
      "## Keturi dovanų tipai",
      "### Pomėgio papildymas",
      "Sportui, muzikai ar žaidimams skirti aksesuarai tinka tik žinant tikslią veiklą. Profesionaliai įrangai galioja savi parametrai; jei jų nežinote, geriau pasirinkti patirtį arba leisti jam apsispręsti pačiam.",
      "### Bendras laikas",
      "Pasivaikščiojimas su suplanuota stotele, bilietas ar namuose surengtas degustavimo vakaras yra dovana tik tada, kai jūs pasirūpinate organizavimu. Vien pažadas „kada nors ką nors nuveiksime“ gali likti neįgyvendintas.",
      "### Asmeniškas prisiminimas",
      "Nuotrauka ar laiškas tinka, jeigu jis mėgsta tokius gestus. Jei ne, net labai gražiai paruošta dėžutė gali nepatikti. Porai, kuri vertina kūrybą, tinka ir kartu sukuriamas daiktas — bet prieš perkant įvertinkite laiką bei norą tuo užsiimti.",
      "### Praktiškas daiktas",
      "Rinkitės ne „naudingą apskritai“, o naudingą jo konkrečiai rutinai. Vieno gerai pasirinkto daikto užtenka; nereikia jo slėpti po atsitiktinių smulkmenų rinkiniu.",
      "Kai pasirinksite kandidatą, paklauskite: ar jis jau turi analogą, ar panaudos per mėnesį ir ar dovana tiks jūsų santykiui? Jei neaišku, paklauskite jo tiesiai. Staigmena nėra vertingesnė už tinkamą dovaną.",
    ],
  },
  {
    id: "lt-gifts-girlfriend",
    slug: "dovanos-merginai",
    title: "Dovanos merginai: asmeniška idėja be klišių",
    excerpt: "Kaip derinti jos pomėgius, santykio etapą, biudžetą ir kartu praleidžiamą laiką renkant dovaną merginai.",
    category: "Dovanos pagal gavėją",
    day: "2026-10-06",
    image: "dovanos-merginai.webp",
    imageAlt: "Supakuota dovana, nuotraukų juosta ir gėlė ant stalo",
    relatedIds: ["lt-gifts-boyfriend", "lt-gifts-couple", "lt-gifts-personalized"],
    body: [
      "Dovana merginai tampa asmeniška ne dėl širdelės ant pakuotės, o dėl teisingai pastebėto poreikio. Gal ji neseniai pradėjo naują pomėgį, ieškojo konkrečios knygos arba nori daugiau neskubaus laiko kartu. Vienas toks signalas vertingesnis už šimtą universalių rekomendacijų.",
      "## Stebėkite, bet nespėliokite",
      "Užsirašykite, ką ji pati sakė norinti ir ko nemėgsta. Nemaišykite „man atrodo, kad jai tiktų“ su jos pasirinkimu. Jei perkate odos priežiūros priemonę, parfumeriją ar drabužį be tikslaus produkto, lengva nepataikyti. Tokiais atvejais patogiau suteikti pasirinkimą arba eiti rinktis kartu.",
      "## Dovana pagal santykio etapą",
      "Naujo santykio pradžioje geriau rinktis mažą, aiškų gestą: jos mėgstamo renginio bilietą, knygą iš norų sąrašo ar pasiūlymą kartu išbandyti veiklą. Ilgesniame santykyje galima remtis bendru prisiminimu — albumu, išvyka ar rankomis sukuriamu objektu. Tačiau kiekvienas iš jų turi tikti būtent jai, o ne jūsų įsivaizduotam romantikos scenarijui.",
      "## Kai norisi patirties",
      "Viena suplanuota diena dažnai jaučiasi geriau nei abstraktus kuponas. Pasiūlykite veiklą, laiką ir transportą, bet palikite jai galimybę datą keisti. Patirtį rinkitės pagal abiejų galimybes: staigmena, kurią sunku įtraukti į kalendorių, tampa rūpesčiu.",
      "## Kai norisi daikto",
      "Pasitikrinkite, ar jis turės vietą ir paskirtį. Gražus interjero akcentas netinka, jei nežinote jos namų stiliaus. Personalizuotam daiktui rinkitės prasmingą datą arba detalę, o ne atsitiktinai atspausdintą vardą. Jei dovana susijusi su jūsų bendru gyvenimu, iš anksto pasirūpinkite kokybiška nuotrauka ar teisingu užrašu.",
      "## Greitas sprendimo testas",
      "Ar ji pati galėtų paaiškinti, kodėl ši dovana tinka? Ar jai nereikės papildomai mokėti arba rūpintis priežiūra? Ar ji gali dovaną panaudoti per artimiausias savaites? Jei atsakymas į vieną klausimą „ne“, pakeiskite idėją arba paklauskite jos nuomonės.",
      "Daugiau bendrų veiklų variantų rasite [[dovanų porai gide|article:lt-gifts-couple]]. Svarbiausia — ne įspūdis nuotraukoje, o jos tikras džiaugsmas atidarius dovaną.",
    ],
  },
  {
    id: "lt-gifts-female-friend",
    slug: "dovanos-draugei",
    title: "Dovanos draugei: nuo mažo dėmesio iki bendro nuotykio",
    excerpt: "Platoniškai draugystei skirtos idėjos pagal jūsų bendrą istoriją, atstumą ir biudžetą.",
    category: "Dovanos pagal gavėją",
    day: "2026-10-07",
    image: "dovanos-draugei-v2.webp",
    imageAlt: "Ryškus popieriaus koliažas: draugės dalijasi dovana lauke",
    relatedIds: ["lt-christmas-friends-2026", "lt-gifts-male-friend", "lt-gifts-experiences"],
    body: [
      "Dovanos draugei nereikia paversti iškilmingu pareiškimu. Dažnai geriausiai veikia maža, tiksli mintis apie tai, kas jums abiem būdinga: bendras filmas, kelionė, juokas ar ilgi pasivaikščiojimai. Skirtingai nuo dovanos partnerei, čia verta saugoti draugystės lengvumą.",
      "## Jei draugė gyvena netoliese",
      "Pakvieskite į konkretų bendrą užsiėmimą: pasivaikščiojimą nauju maršrutu, vakarą su stalo žaidimu arba dirbtuves, kurios jai tikrai įdomios. Pasiūlykite dvi galimas datas. Tai nedidelis, bet svarbus skirtumas tarp realaus plano ir tuščio pažado.",
      "## Jei jus skiria atstumas",
      "Tinka mažas išsiunčiamas daiktas, siejamas su jūsų istorija: viena nuotrauka su paaiškinimu, jos mėgstamos arbatos porcija ar knyga, apie kurią kalbėjotės. Prieš siųsdami patikrinkite tikrąją sumą su pristatymu ir ar siunta atvyks laiku.",
      "## Jei nežinote jos naujų pomėgių",
      "Neapsimeskite, kad žinote. Paklauskite, ko ji šiuo metu klausosi, skaito ar nori išbandyti. Jei staigmeną norite išlaikyti, sužinokite kryptį, o ne konkretų produktą. Dovana pagal seną pomėgį, kurio žmogus jau atsisakė, gali atrodyti neatidi.",
      "## Ko vengti",
      "Kosmetika, kvapai, drabužiai ir mitybos produktai yra jautrūs skoniui ar poreikiams. Juos rinkitės tik jei turite tikslią informaciją. Nepridėkite penkių atsitiktinių smulkmenų vien tam, kad dėžė atrodytų pilna; tai neišsprendžia tinkamumo problemos.",
      "## Praktinis pasirinkimas",
      "Surašykite tris idėjas ir kiekvienai pažymėkite: ar draugė ją panaudos, ar ją lengva priimti, ar ji telpa į jūsų bendrą dovanų įprotį. Laimi ne brangiausia idėja, o ta, kuri turi geriausią atsakymą į visus tris klausimus.",
      "Jeigu proga yra Kalėdos, papildomai peržiūrėkite [[dovanų draugams gidą|article:lt-christmas-friends-2026]]. Ten rasite būdą susitarti dėl biudžeto nepatogumo nesukeliant.",
    ],
  },
  {
    id: "lt-gifts-male-friend",
    slug: "dovanos-draugui",
    title: "Dovanos draugui: konkretūs pasirinkimo kriterijai vietoj stereotipų",
    excerpt: "Kaip draugui rasti naudojamą dovaną pagal bendrą veiklą ir nepaslysti perkant hobio įrangą.",
    category: "Dovanos pagal gavėją",
    day: "2026-10-08",
    image: "dovanos-draugui-v2.webp",
    imageAlt: "Draugai apsikeičia dovana saulėtame riedlenčių parke",
    relatedIds: ["lt-christmas-friends-2026", "lt-gifts-female-friend", "lt-gifts-boyfriend"],
    body: [
      "Draugui dovana gali priminti bendrą veiklą arba pašalinti mažą jo kasdienį nepatogumą. Ji neprivalo būti „vyriška“ ar brangi. Renkantis svarbiau, ar draugas tikrai ją naudos ir ar dovana nesukurs neproporcingo įsipareigojimo atsilyginti.",
      "## Pomėgis: domėkitės detalėmis",
      "Žinoti, kad draugas žaidžia, važiuoja dviračiu ar kepa duoną, dar nepakanka konkrečiam priedui išrinkti. Paklauskite, kokį modelį jis naudoja, kokias medžiagas renkasi ir ko jam trūksta. Jei tokių duomenų neturite, saugiau dovanoti bilietą, laiką kartu arba pomėgio parduotuvės kuponą su jūsų paaiškinimu.",
      "## Trys realūs scenarijai",
      "### Draugas, su kuriuo retai susitinkate",
      "Kvietimas į konkretų renginį arba suplanuotas susitikimas gali turėti daugiau vertės nei kurjeriu atsiųstas daiktas. Neužsakykite negrąžinamo bilieto, kol nesuderinote datos.",
      "### Draugas, kuris nuolat ką nors kuria",
      "Peržiūrėkite jo įrankių rinkinį prieš pirkdami. Mažas kokybiškas papildymas yra gerai, jei tiksliai žinote dydį ar suderinamumą. Dar vienas pradinis rinkinys patyrusiam žmogui dažniausiai nereikalingas.",
      "### Draugas, kuris vertina humorą",
      "Vidinis pokštas veikia, kai jį supranta gavėjas ir dovana nepažemina jo kitų akivaizdoje. Juokingą detalę galima pridėti prie naudojamo daikto, bet vien pokštas neturėtų tapti daiktu, kurį jis privalės saugoti.",
      "## Biudžeto riba",
      "Iš anksto pasakykite, jei draugų grupė keičiasi dovanomis. Nedidelis limitas skatina tikslumą, o ne prastą kokybę. Į kainą įtraukite siuntimą ir pakuotę; jei suma viršija ribą, rinkitės kitą idėją, ne slapta didinkite spaudimą kitiems.",
      "Prieš pirkdami sau atsakykite, ką draugas su dovana darys pirmą savaitę. Jei negalite sugalvoti, tikėtina, kad ji paremta reklamos vaizdu, o ne jo gyvenimu.",
    ],
  },
  {
    id: "lt-gifts-couple",
    slug: "dovanos-porai-idejos",
    title: "Dovanos porai: 4 kryptys pagal tai, kaip jie leidžia laiką",
    excerpt: "Nešventinis gidas poros dovanai: bendra veikla, namų ritualas, prisiminimas ar naudinga detalė.",
    category: "Dovanos porai",
    day: "2026-10-09",
    image: "dovanos-porai-v2.webp",
    imageAlt: "Grafiška iliustracija: pora kartu kuria mažą sodą miesto terasoje",
    relatedIds: ["lt-couple-ideas", "lt-christmas-couple", "lt-gifts-experiences", "lt-hand-casting-guide"],
    productRecommendation: true,
    body: [
      "Dovana porai turi tikti dviem žmonėms. Vienas gali mėgti keliauti, kitas — jaukius vakarus namuose; vienas — kurti, kitas — stebėti. Todėl prieš renkantis svarbu rasti jų tikrą bendrą vardiklį, o ne pirkti tai, kas nuotraukoje atrodo romantiška.",
      "## 1. Bendra veikla",
      "Vakarienė, dirbtuvės ar trumpa išvyka tinka, jei abu galės dalyvauti ir pasirinkti laiką. Patikrinkite vietą, trukmę, papildomas išlaidas ir galiojimą. Bilietai konkrečiai dienai gali būti blogesnė dovana nei lankstus planas, jei nežinote poros grafiko.",
      "## 2. Namų ritualas",
      "Jei pora mėgsta laiką namuose, rinkitės tai, kas pagerins jau esantį įprotį: žaidimo vakarą, bendrą maisto ruošimą ar skaitymo kampą. Dideli interjero daiktai rizikingi, jei nežinote jų skonio ir vietos namuose. Mažesnis, naudojamas dalykas dažnai saugesnis.",
      "## 3. Bendras prisiminimas",
      "Nuotraukų knyga, asmeniškas laiškas ar kartu sukurtas objektas tinka, kai pora vertina prisiminimus. Rankų liejimo rinkinys gali būti prasmingas, jei abu norėtų skirti vakarą procesui ir išsaugoti rezultatą. Jei bent vienam tokia veikla nepatinka, rinkitės kitą būdą įamžinti istoriją. Praktinį pasiruošimą aprašome [[rankų liejimo gide|article:lt-hand-casting-guide]].",
      "## 4. Praktinis bendras daiktas",
      "Jis veikia tik tada, jei tikrai naudojamas abiejų. Kavos aparatas vienam kavos geriančiam žmogui nėra dovana porai. Prieš pirkdami paklauskite, kaip pora jau leidžia rytus ar savaitgalius; naudokite atsakymą kaip pasirinkimo filtrą.",
      "## Kaip išsirinkti iš keturių",
      "Kiekvienai krypčiai skirkite po vieną balą už tinkamumą abiem, įgyvendinimą per mėnesį ir bendrą kainą be paslėptų papildymų. Mažiausiai vieną balą gavusios krypties atsisakykite. Toks paprastas testas padeda nepirkti dovanos vien dėl pakuotės.",
      "Porai, kuri laukia kūdikio, kraustosi arba turi itin užimtą sezoną, dovanokite lanksčiai. Gera dovana prisitaiko prie jų gyvenimo, o ne reikalauja prisitaikyti prie jos.",
    ],
  },
  {
    id: "lt-gifts-mother",
    slug: "dovanos-mamai",
    title: "Dovanos mamai: ką rinktis, kai norisi parodyti dėmesį, o ne pridėti rūpesčių",
    excerpt: "Idėjos mamai pagal jos įpročius ir laiką: asmeniškas prisiminimas, praktiška pagalba ar kartu suplanuota patirtis.",
    category: "Dovanos šeimai",
    day: "2026-10-12",
    image: "dovanos-mamai-v2.webp",
    imageAlt: "Mama ir suaugusi dukra kartu vaikšto spalvingame gėlių turguje",
    relatedIds: ["lt-christmas-parents-2026", "lt-gifts-father", "lt-gifts-meaningful"],
    body: [
      "Mamą lengva apdovanoti tuo, kas naudinga visiems namuose, bet ne jai pačiai. Nauja keptuvė ar dulkių siurblys gali išspręsti šeimos poreikį, tačiau kaip asmeninė dovana tiks tik tada, jei ji pati to norėjo. Pirmiausia pagalvokite, ką mama renkasi dėl savęs, ne dėl kitų.",
      "## Trys klausimai prieš idėjų sąrašą",
      "Kada ji paskutinį kartą minėjo norinti laiko sau? Ką mėgsta veikti, kai nieko nereikia organizuoti kitiems? Ar jai patogiau gauti daiktą, patirtį ar pagalbą? Atsakymai padės atmesti dovanas, kurios tik gražiai atrodo internete.",
      "## Jei ji vertina bendrą laiką",
      "Pasiūlykite konkretų planą: pasivaikščiojimą su kava, apsilankymą parodoje ar vakarienę, kurią ruošite jūs. Pasirūpinkite bilietais, transportu ar maistu, bet palikite galimybę pakeisti datą. Jūsų suplanuotas laikas skiriasi nuo neapibrėžto pažado „būtinai kada nors susitiksime“.",
      "## Jei ji vertina prisiminimus",
      "Atrinkite kelias aiškias šeimos nuotraukas, surašykite jų kontekstą ir sukurkite mažą albumą. Patikrinkite, ar nuotraukos tinkamos rodyti ir ar mama norėtų jas laikyti matomoje vietoje. Jeigu ne, uždaromas albumas geriau už rėmelį.",
      "## Jei ji vertina praktiškumą",
      "Pasirinkite vieną jos pačios įvardytą nepatogumą: trūkstamą skaitymo šviesą, susidėvėjusį pomėgio įrankį arba paslaugą, kurios ji vis neprisiverčia užsakyti. Nepirkite pagal abstraktų „mamoms patinka“. Patikrinkite matmenis, suderinamumą ir grąžinimą.",
      "## Jei norite padovanoti pagalbą",
      "Pagalba turi būti konkreti: „šeštadienį 11 val. atvažiuosiu sutvarkyti nuotraukų archyvo, jei tau tinka“. Tuščias pažadas „skambink, jei ko reikės“ perkelia planavimą jai. Jei ji nenori pagalbos, gerbkite tai ir rinkitės kitą dovaną.",
      "Prieš įteikdami patikrinkite, ar dovana nereikalauja papildomų mokėjimų, sudėtingo užsakymo ar vietos, kurios ji neturi. Geras dėmesys yra lengvas priimti. Tėvams skirtų bendrų pasirinkimų ieškokite [[Kalėdų gide|article:lt-christmas-parents-2026]].",
    ],
  },
  {
    id: "lt-gifts-father",
    slug: "dovanos-teciui",
    title: "Dovanos tėčiui: nuo konkretaus pomėgio iki laiko kartu",
    excerpt: "Kaip nesuklysti su įrankiais, technika ar patirtimi ir išrinkti tėčiui dovaną pagal tai, ką jis pats vertina.",
    category: "Dovanos šeimai",
    day: "2026-10-13",
    image: "dovanos-teciui-v2.webp",
    imageAlt: "Juodai baltas kadras: tėvas su suaugusiu sūnumi taiso dviratį",
    relatedIds: ["lt-christmas-parents-2026", "lt-gifts-mother", "lt-gifts-brother"],
    body: [
      "Tėčiui dažnai dovanojami įrankiai ar technologijos vien dėl įpročio. Tačiau geras pirkinys priklauso nuo jo konkretaus modelio, veiklos ir poreikio. Jeigu tėtis nesidomi technika, dovanų kategorijos etiketė to nepakeis.",
      "## Išsiaiškinkite, kas jam svarbu",
      "Pasirinkite vieną iš trijų krypčių: ką jis mėgsta veikti, ką vis atideda arba kokį bendrą laiką vertintų. Užrašykite konkrečius pavyzdžius, ne vien „mėgsta gaminti“: gal jis kas savaitę kepa duoną, taiso dviračius ar žiūri senus filmus. Tada dovaną galima susieti su realiu veiksmu.",
      "## Pomėgio dovana be klaidos",
      "Jei norite pirkti įrankį, išsiaiškinkite dydį, baterijų sistemą ir turimą įrangą. Patyręs žmogus dažnai turi aiškius reikalavimus, todėl staigmena neturėtų jų ignoruoti. Jei abejojate, rinkitės priedą, kurį jis pats nurodė, arba kartu nueikite išsirinkti.",
      "## Patirtis, kuri nėra papildoma užduotis",
      "Bendra išvyka, koncertas ar vakarienė tinka, jei pasiūlote tikrą datą ir pasirūpinate organizavimu. Tėčiui, kuris nemėgsta minios, net puikus koncertas netiks. Vertinkite jo komfortą, ne tik renginio populiarumą.",
      "## Asmeniškas, bet ne sentimentalumo prievolė",
      "Nuotrauka ar laiškas gali būti vertingi, jei jūsų šeimoje tokius gestus priima natūraliai. Jeigu tėtis labiau vertina veiklą, atgaivinkite bendrą tradiciją: suplanuokite remontą, išvyką ar gaminimą kartu. Dovana gali būti proga vėl nuveikti tai, kas anksčiau jungė.",
      "## Ko vengti",
      "Nedovanokite darbo įrankio kaip užuominos, kad jis turėtų daugiau taisyti namuose. Nepirkite sveikatai ar amžiui skirtų priemonių, jei jis pats jų neprašė. Nesukurkite prenumeratos, kurią vėliau turės apmokėti pats.",
      "Prieš pirkdami paklauskite, ar dovana jam suteiks malonumo, ar tik pareigą. Jei abejojate, nuoširdus klausimas apie jo norą gali būti naudingesnis už tariamą staigmeną.",
    ],
  },
  {
    id: "lt-gifts-grandparents",
    slug: "dovanos-seneliams",
    title: "Dovanos seneliams: prisiminimai, ryšys ir patogus naudojimas",
    excerpt: "Senelių dovanų atranka be amžiaus stereotipų: aiškus naudojimas, bendras laikas ir jų pačių pomėgiai.",
    category: "Dovanos šeimai",
    day: "2026-10-14",
    image: "dovanos-seneliams.webp",
    imageAlt: "Seneliai kartu varto šeimos nuotraukų albumą prie arbatos",
    relatedIds: ["lt-christmas-parents-2026", "lt-gifts-mother", "lt-gifts-father"],
    body: [
      "Seneliai nėra viena pomėgių grupė. Vieni keliauja, kiti augina augalus, žaidžia su anūkais ar kuria rankdarbius. Rinkdamiesi dovaną pirmiausia prisiminkite jų individualų gyvenimą ir tik tada vertinkite, ar daiktas bus patogus naudoti.",
      "## Prisiminimų dovana, kurioje darbas jau atliktas",
      "Nuotraukų albumas tinka, kai jūs patys atrinkote gerus kadrus, surašėte datas ir vardus, patikrinote spausdinimo kokybę. Neįteikite dėžės su šimtais nesurūšiuotų nuotraukų kaip tariamai baigto projekto. Jei šeimos istorija jautri, pasirinkite tik tas nuotraukas, kurias seneliai norės matyti.",
      "## Bendras laikas be skubėjimo",
      "Pasivaikščiojimas, pietūs ar bendras recepto gaminimas dažnai vertingas tada, kai suplanuotas patogiu tempu. Pasiūlykite pasirinkti datą, pasirūpinkite transportu, tačiau nepriimkite sprendimo už juos. Jie gali turėti aktyvesnį kalendorių, nei manote.",
      "## Daiktas, kurį patogu priimti",
      "Jei perkate techniką, įvertinkite ne stereotipinį „paprastumą senjorams“, o ar konkrečiam žmogui patiks sąsaja ir ar padėsite ją įdiegti. Pirkdami pomėgio daiktą patikrinkite tikslius matmenis, medžiagas ir esamus priedus.",
      "## Jei dovanojate abiem",
      "Bendra dovana turi būti naudojama abiejų. Jei vienas nemėgsta nuotraukų albumų, o kitas jų laukia, nedarykite kompromiso vien dėl pakuotės: įteikite atskiras mažesnes dovanas. Pora nėra vienas žmogus.",
      "## Ko nedaryti",
      "Nedovanokite didelio daikto, kuriam jie neturi vietos, arba paslaugos su sudėtinga registracija. Dovana neturėtų būti užuomina apie amžių ar sveikatą. Jei planuojate pagalbą, pasiūlykite konkretų darbą ir paklauskite, ar jos tikrai norima.",
      "Prie dovanos pridėkite vieną sakinį apie tai, kodėl pasirinkote būtent jiems. Tai gali būti asmeniškiau už bet kokią etiketę „seneliams“.",
    ],
  },
  {
    id: "lt-gifts-brother",
    slug: "dovanos-broliui",
    title: "Dovanos broliui: idėjos pagal jūsų ryšį ir jo dabartinį gyvenimą",
    excerpt: "Pomėgio, bendro laiko ir mažų praktiškų dovanų broliui atranka, nepasikliaujant vaikystės prisiminimais vienais.",
    category: "Dovanos šeimai",
    day: "2026-10-15",
    image: "dovanos-broliui-v2.webp",
    imageAlt: "Broliai ar seserys apsikeičia dovana žygiuodami snieguotu taku",
    relatedIds: ["lt-gifts-sister", "lt-gifts-male-friend", "lt-gifts-father"],
    body: [
      "Brolį pažįstate seniai, bet tai nereiškia, kad žinote dabartinius jo pomėgius. Dovana, paremta vien tuo, ką jis mėgo mokykloje, gali nepataikyti. Paklauskite, ką jis šiuo metu veikia savaitgaliais ir ko jam trūksta naujame gyvenimo etape.",
      "## Jei gyvenate skirtinguose miestuose",
      "Dovaną galima susieti su susitikimu: pasiūlykite suplanuotą išvyką, renginį ar vakarą kartu. Įvertinkite atvykimo kainą ir laiką; nereikalaukite, kad jis pats finansuotų didžiąją dalį jūsų dovanotos patirties.",
      "## Jei dalijatės pomėgiu",
      "Bendras sportas, muzika ar žaidimai leidžia pasirinkti labai tiksliai. Vis tiek pasitikrinkite konkretų modelį ir ar jis jo neturi. Jei perkate hobio įrangą, grąžinimo galimybė svarbesnė už staigmenos išsaugojimą.",
      "## Jei jūsų skoniai skiriasi",
      "Neverskite jo pamėgti jūsų veiklos per dovaną. Užuot pirkę jam savo mėgstamą knygą ar žaidimą, sužinokite jo pasirinkimą. Jei informacijos mažai, nedidelis neutralus gestas ir laikas kartu geresni už spėliojimą.",
      "## Humoras su pagarba",
      "Vidinis šeimos pokštas gali būti gera detalė, bet neturėtų gėdinti brolio kitų akivaizdoje. Jei dovana labai asmeniška, įteikite ją privačiai. Nereikalaukite, kad suvenyras visada būtų rodomas namuose.",
      "## Greitas filtras",
      "Ar jis panaudos dovaną per mėnesį? Ar ji atitinka jo dabartinį, o ne vaikystės gyvenimą? Ar visa suma su papildomais priedais telpa į jūsų ribą? Jei bent vienas atsakymas „ne“, idėją keiskite. [[Gide sesei|article:lt-gifts-sister]] aptariame panašius, bet ne tapačius šeimos pasirinkimo klausimus.",
    ],
  },
  {
    id: "lt-gifts-sister",
    slug: "dovanos-sesei",
    title: "Dovanos sesei: kaip pasirinkti tarp bendros istorijos ir naujų pomėgių",
    excerpt: "Sesei skirta dovana gali atspindėti jūsų ryšį, bet neturi ignoruoti to, kuo ji gyvena šiandien.",
    category: "Dovanos šeimai",
    day: "2026-10-16",
    image: "dovanos-sesei-v2.webp",
    imageAlt: "Ryški retro iliustracija: seserys juokiasi miesto transporte",
    relatedIds: ["lt-gifts-brother", "lt-gifts-female-friend", "lt-gifts-personalized"],
    body: [
      "Sesei lengva išrinkti nostalgišką dovaną, nes turite daug bendrų prisiminimų. Tačiau geras pasirinkimas turėtų kalbėti ir apie tai, kas ji yra dabar. Jei neseniai pakeitė darbą, miestą ar pomėgį, įsiklausykite į šį etapą, o ne vien į vaikystės istoriją.",
      "## Kada tinka asmeniškas prisiminimas",
      "Viena jūsų abiejų nuotrauka, mažas albumas ar laiškas gali būti stipri dovana, jei sesė mėgsta tokius daiktus. Atsirinkite tik tuos kadrus, kuriuos ji pati norėtų matyti. Intymi šeimos istorija nebūtinai skirta rėmeliui ant darbo stalo.",
      "## Kada geriau remtis nauju pomėgiu",
      "Jei sesė neseniai pradėjo piešti, bėgioti ar gaminti, neperkite pirmo pasitaikiusio pradinio rinkinio. Paklauskite, ko jai reikia šiuo etapu. Patyrusiam žmogui dažnai reikia vieno konkretaus įrankio, o ne bendro „kūrybos“ rinkinio.",
      "## Laikas kartu",
      "Jei retai susitinkate, pasiūlykite veiklą, kurią abi ar abu mielai darytumėte: pasivaikščiojimą, koncertą, maisto gaminimą. Nupirkus bilietus be datos suderinimo, patirtis gali virsti kalendoriaus problema. Verčiau pirmiausia susitarti dėl laiko.",
      "## Dydis, kvapas ir skonis",
      "Apranga, kosmetika ir kvapai tinka tik žinant konkretų jos pasirinkimą. Net artimas šeimos ryšys nėra garantija, kad pataikysite. Jei nesate tikri, rinkitės daiktą be dydžio arba leiskite jai dalyvauti renkantis.",
      "## Dvi idėjos vietoj dešimties",
      "Užrašykite vieną idėją iš jūsų bendros istorijos ir vieną iš dabartinio jos gyvenimo. Palyginkite, kurią ji lengviau panaudos ir kuriai mažiau papildomų sąlygų. Dovana neturi įrodyti, kad viską apie ją žinote; ji turi parodyti, kad domitės.",
    ],
  },
  {
    id: "lt-gifts-personalized",
    slug: "personalizuotos-dovanos-kaip-issirinkti",
    title: "Personalizuotos dovanos: kada vardas, nuotrauka ar rankų darbas turi prasmę",
    excerpt: "Praktinis personalizavimo gidas: ką suasmeninti, kaip patikrinti maketą, terminą ir gavėjo privatumą.",
    category: "Personalizuotos dovanos",
    day: "2026-10-19",
    image: "personalizuotos-dovanos-v2.webp",
    imageAlt: "Spalvinga grafinė kompozicija su rėmeliu ir suasmeninamo daikto formomis",
    relatedIds: ["lt-hand-casting-guide", "lt-gifts-sentimental", "lt-gifts-meaningful"],
    productRecommendation: true,
    body: [
      "Personalizacija nėra vien vardas ant daikto. Geriausiai ji veikia, kai pasirinkta detalė reiškia ką nors gavėjui: konkreti nuotrauka, bendras prisiminimas, jo mėgstama spalva ar daiktas, pagamintas kartu. Atsitiktinis inicialas ant nereikalingo gaminio nepadaro dovanos naudingos.",
      "## Pirmiausia pasirinkite patį daiktą",
      "Paklauskite, ar gavėjas naudotų šį daiktą net be personalizacijos. Jei ne, papildomas užrašas vargu ar išgelbės pirkinį. Puodelis tinka tam, kas jį iš tikrųjų naudos; albumas — tam, kas mėgsta vartyti nuotraukas; kūrybinis rinkinys — tam, kas norėtų dalyvauti procese.",
      "## Vardas ar data",
      "Patikrinkite rašybą, linksnį, lietuviškas raides, datą ir maketo peržiūrą prieš patvirtindami užsakymą. Kai kurie gaminiai po personalizavimo negali būti grąžinti dėl vien persigalvojimo; konkrečias pardavėjo sąlygas skaitykite prieš mokėdami. Užrašą rinkitės trumpą, kad jis nepersvertų daikto paskirties.",
      "## Nuotrauka",
      "Rinkitės ryškų originalų failą, ne suspaustą pokalbio programėlės kopiją. Patikrinkite kadravimą ir ar visi vaizduojami žmonės norėtų, kad ši nuotrauka būtų atspausdinta ar rodoma. Jei albumas skirtas privačiam laikymui, formatas gali būti jaukesnis už didelį sienos paveikslą.",
      "## Bendras rankų darbas",
      "Jis suteikia dovanai asmeninio veiksmo, bet reikalauja laiko. Rankų liejimo rinkinys gali tikti porai ar šeimai, kuriai įdomus kūrybinis procesas ir pats rezultatas. Prieš užsakant verta perskaityti [[išsamų pasiruošimo gidą|article:lt-hand-casting-guide]] ir gamintojo komplektaciją. Nesirinkite jo žmogui, kuris aiškiai nemėgsta rankdarbių.",
      "## Gamybos ir pristatymo terminas",
      "Personalizuotas gaminys gali turėti du laikotarpius: gamybą ir siuntimą. Patikrinkite abu bei atsarginį variantą, jei terminas kritinis. Neužsisakykite vien remdamiesi bendru pažadu „greitas pristatymas“ — žiūrėkite konkretų užsakymą.",
      "## Galutinis klausimas",
      "Ar personalizacija padeda gavėjui pamatyti, kodėl ši dovana būtent jo? Jei ji tik užpildo tuščią vietą ant gaminio, rinkitės paprastesnį daiktą ir nuoširdų paaiškinimą. Prasmė yra pasirinkime, ne spaudos technologijoje.",
    ],
  },
  {
    id: "lt-gifts-meaningful",
    slug: "prasmingos-dovanos-idejos",
    title: "Prasmingos dovanos: kaip atskirti tikrą dėmesį nuo brangaus gesto",
    excerpt: "Keturi klausimai, padedantys išrinkti prasmingą dovaną be spaudimo pirkti daugiau ar kurti pernelyg sentimentalią istoriją.",
    category: "Dovanų idėjos",
    day: "2026-10-20",
    image: "prasmingos-dovanos-v2.webp",
    imageAlt: "Du žmonės kartu sodina medį bendruomenės sode",
    relatedIds: ["lt-gifts-sentimental", "lt-gifts-experiences", "lt-gifts-personalized"],
    body: [
      "Prasminga dovana nėra automatiškai brangi, rankų darbo ar sentimentali. Ji turi aiškų ryšį su gavėjo gyvenimu. Vienam žmogui tai bus laikas kartu, kitam — tiksliai parinktas įrankis, trečiam — prisiminimas, kurį norisi išsaugoti.",
      "## Keturi atrankos klausimai",
      "Ką žmogus jau vertina? Ką jis galės su dovana daryti? Kokių papildomų išlaidų ar pareigų ji sukurs? Ar pasirinkimą galite paaiškinti vienu tikru pastebėjimu? Jei atsakymai konkretūs, tikimybė pataikyti didesnė nei renkant pagal etiketę „prasminga“.",
      "## Maža, bet tiksli dovana",
      "Rėmelyje įdėta nuotrauka iš svarbios dienos, jo paties minėta knyga ar jūsų iškeptas mėgstamas patiekalas gali kainuoti nedaug. Tačiau neapsimeskite, kad bet kuri nuotrauka yra reikšminga. Atrinkite tą, kurios istoriją gavėjas atpažins.",
      "## Laikas ir paslaugumas",
      "Bendras vakaras, pagalba su konkrečiu darbu ar išvyka gali būti prasmingi, jei dalyvausite patys ir pasirūpinsite organizavimu. „Kada nors padėsiu“ nėra užbaigta dovana. Sutarkite datą arba aiškią jos pasirinkimo tvarką.",
      "## Kai dovana turi likti ilgam",
      "Ilgaamžis daiktas geras tik jei žmogus nori jį laikyti. Šeimos albumas ar kartu sukurtas objektas gali išlikti kaip ryšio ženklas; tačiau neverskite gavėjo jo eksponuoti. Ypač jautriems prisiminimams palikite privatumą.",
      "## Kada prasmė tampa spaudimu",
      "Per didelė dovana gali įpareigoti atsilyginti. Gyvūnas, prenumerata ar kelionė gali reikalauti priežiūros, mokėjimų ir laiko. Jeigu šių dalykų gavėjas nepasirinko, „prasmingumas“ yra labiau dovanojančiojo istorija nei gavėjo džiaugsmas.",
      "Galiausiai rinkitės ne tarp „praktiška“ ir „jausminga“, o tarp tinkama ir netinkama. Jausmas gali slypėti praktiniame daikte, jei aišku, kodėl jis parinktas. Daugiau formų aptariame [[sentimentalių dovanų gide|article:lt-gifts-sentimental]].",
    ],
  },
  {
    id: "lt-gifts-sentimental",
    slug: "sentimentalios-dovanos",
    title: "Sentimentalios dovanos: kaip išsaugoti prisiminimą neperžengiant ribos",
    excerpt: "Nuotraukų, laiškų ir bendrų kūrybinių dovanų pasirinkimo kriterijai, kai svarbi ir istorija, ir gavėjo privatumas.",
    category: "Dovanų idėjos",
    day: "2026-10-21",
    image: "sentimentalios-dovanos-v2.webp",
    imageAlt: "Akvarelėje dvi kartos kartu žiūri į žvaigždėtą dangų",
    relatedIds: ["lt-gifts-meaningful", "lt-gifts-personalized", "lt-hand-casting-guide"],
    productRecommendation: true,
    body: [
      "Sentimentali dovana primena ryšį, tačiau ji turi būti maloni gavėjui, ne vien ją ruošiančiam žmogui. Kai kurie mėgsta nuotraukas ant sienos, kiti nori prisiminimus laikyti privačiai. Nuo šio skirtumo priklauso formatas, ne jausmo stiprumas.",
      "## Nuotrauka: viena ar visas albumas?",
      "Viena nuotrauka tinka, jei kadras aiškus ir žmogus norės jį matyti kasdien. Albumas geresnis, kai istorija ilgesnė arba asmeniškesnė. Atrinkite tik reikalingus vaizdus, prie jų užrašykite kontekstą ir patikrinkite, ar kiti juose esantys žmonės sutiktų su tokiu naudojimu.",
      "## Laiškas: būkite konkretūs",
      "Nereikia rašyti didelio atsiminimų romano. Užtenka vieno epizodo, už kurį norite padėkoti, ir vieno sakinio apie tai, ką žmoguje vertinate dabar. Venkite perdėto viešo jausmų demonstravimo, jei gavėjui tai nepatogu. Laišką galima įdėti į voką, kad jis pats pasirinktų, kada skaityti.",
      "## Bendras kūrimas",
      "Rankų darbo dovana gali būti jūsų pačių pagaminta arba kartu atliekamas procesas. Pastarajam reikia sutikimo ir laiko: net prasmingas rankų liejimo rinkinys netiks tam, kas nemėgsta kūrybinių veiklų. Prieš siūlydami įvertinkite instrukciją, vietą ir tai, kur bus laikomas rezultatas.",
      "## Jautrūs prisiminimai",
      "Netekties, skyrybų ar sudėtingų šeimos įvykių nuotraukos gali sukelti netikėtų jausmų. Jei nesate tikri, klauskite gavėjo arba rinkitės neutralesnę dabarties akimirką. Dovana neturėtų priversti žmogaus viešai išgyventi to, ką jis norėtų laikyti sau.",
      "## Kaip nepersistengti",
      "Nepaverskite dovanos testu, ar gavėjas prisimena tą patį taip pat stipriai. Įteikite ją be reikalavimo tuoj pat kabinti, fotografuoti ar demonstruoti. Pakanka leisti jam priimti istoriją savaip.",
      "Jei dvejojate tarp prisiminimo ir praktiško daikto, perskaitykite [[prasmingų dovanų kriterijus|article:lt-gifts-meaningful]]. Kartais geriausias sprendimas yra kasdien naudojamas daiktas su trumpu asmenišku palinkėjimu.",
    ],
  },
  {
    id: "lt-gifts-experiences",
    slug: "dovanos-patirtys-kaip-issirinkti",
    title: "Dovanos-patirtys: kaip išrinkti veiklą, kuria žmogus tikrai pasinaudos",
    excerpt: "Patirties dovanos kontrolinis sąrašas: data, vieta, papildomos išlaidos, galiojimas ir galimybė keisti planus.",
    category: "Dovanų idėjos",
    day: "2026-10-22",
    image: "dovanos-patirtys.webp",
    imageAlt: "Du žmonės keliauja link namelio prie ežero saulėlydžio metu",
    relatedIds: ["lt-gifts-couple", "lt-gifts-meaningful", "lt-gifts-has-everything"],
    body: [
      "Patirties dovana atrodo lengva, nes neužima vietos lentynoje. Tačiau ji gali užimti daug vietos kalendoriuje. Geras kuponas ar bilietas turi derėti su gavėjo laiku, pomėgiais, judėjimo galimybėmis ir papildomomis išlaidomis.",
      "## Pirmas klausimas — ar žmogus pats norėtų šios veiklos?",
      "Nedovanokite ekstremalaus užsiėmimo tam, kuris aiškiai vengia aukščio, arba degustacijos tam, kas nemėgsta ragauti. Staigmena neturėtų versti įveikti baimės. Paklauskite artimo žmogaus arba paties gavėjo, kokias veiklas jis norėtų išbandyti.",
      "## Data ir galiojimas",
      "Bilietas konkrečiai dienai tinka tik suderinus kalendorių. Lankstus kuponas gali būti saugesnis, bet perskaitykite jo galiojimą, rezervavimo tvarką ir keitimo sąlygas. Jei laisvų vietų mažai, net ilgas galiojimas nebūtinai padeda.",
      "## Tikroji dovanos kaina",
      "Pridėkite transportą, nakvynę, maistą ir reikalingą įrangą. Jei dovanojate tik dalį išvykos, pasakykite tai aiškiai. Geriausia, kai gavėjui nereikia netikėtai mokėti už tai, kad panaudotų dovaną.",
      "## Vienam ar kartu?",
      "Kai žmogus nori pabūti vienas, solo veikla gali būti tobula. Jei svarbus ryšys, pasirinkite veiklą dviese ir iš anksto pasiūlykite, kas dalyvaus. Neverskite gavėjo pačiam ieškoti kompanijos ir derinti visų laiko.",
      "## Rezervinis planas",
      "Ligą, blogą orą ar pasikeitusius planus numatyti neįmanoma, bet galima tikrinti perkėlimo taisykles. Lauko veiklai tinka alternatyvi data; trumpai galiojančiam bilietui — galimybė perleisti kitam. Nepirkite griežtų sąlygų dovanos žmogui, kurio grafikas nuolat keičiasi.",
      "Patirtį įteikite su vienu aiškiu sakiniu: ką padovanojote, kokios sąlygos ir kurias dalis jau suorganizavote. Tada ji tampa kvietimu, o ne administracine užduotimi.",
    ],
  },
  {
    id: "lt-gifts-has-everything",
    slug: "dovana-zmogui-kuris-viska-turi",
    title: "Dovana žmogui, kuris viską turi: nustokite ieškoti dar vieno daikto",
    excerpt: "Kaip rasti dovaną žmogui, kuriam nieko netrūksta: laikas, patirtis, pagalba ir apgalvoti sunaudojami dalykai.",
    category: "Dovanų idėjos",
    day: "2026-10-23",
    image: "dovana-zmogui-kuris-viska-turi-v2.webp",
    imageAlt: "Dvi kėdės atviroje terasoje prieš mėlyną jūros horizontą",
    relatedIds: ["lt-gifts-experiences", "lt-gifts-meaningful", "lt-gifts-personalized"],
    body: [
      "Žmogus, kuris „viską turi“, paprastai turi pakankamai daiktų, bet nebūtinai pakankamai laiko, naujų įspūdžių ar dėmesio. Tai nereiškia, kad turite pirkti išskirtinai brangią patirtį. Pirmiausia išsiaiškinkite, ko jis nenori: papildomo daikto, įpareigojimo ar viešos staigmenos.",
      "## Laikas, kurio nereikės organizuoti jam",
      "Pasiūlykite konkretų vakarą kartu, pasirūpinkite vieta ir palikite datą pakeisti. Jei jis daug dirba, dovana turi mažinti planavimo naštą, o ne reikalauti dar vienos rezervacijos. Geras planas dažnai yra vertingesnis už abstraktų kuponą.",
      "## Mažas tikslus sunaudojamas dalykas",
      "Jei žmogus mėgsta konkretų skonį, viena gera sunaudojama dovana gali būti maloni be poreikio ją saugoti. Prieš rinkdamiesi maistą ar gėrimą patikrinkite mitybos ribojimus. Nepirkite milžiniško rinkinio vien todėl, kad jis atrodo įspūdingai.",
      "## Pagalba, kurią galima priimti",
      "Jei žinote darbą, kurį žmogus vis atideda, pasiūlykite konkrečią pagalbą ir laiką. Paklauskite, ar to nori — ne kiekvienas mėgsta, kai kiti perima jo reikalus. Jei jis atsisako, tai nėra dovanos atmetimas; tiesiog reikia kitos idėjos.",
      "## Patirtis be spaudimo",
      "Rinkitės veiklą pagal jo paties smalsumą, ne pagal tai, kas atrodo neįprasta jums. Patikrinkite galiojimą, papildomas išlaidas ir galimybę atidėti. Išsamus sąrašas — [[patirčių dovanų gide|article:lt-gifts-experiences]].",
      "## Kada vis dėlto tinka daiktas",
      "Jei žmogus pats įvardijo tikslų poreikį, geras daiktas nėra blogas pasirinkimas. Tačiau nepirkite dekoro, technologijos ar drabužių be tikslaus skonio ir suderinamumo. Asmeninis užrašas neturi gelbėti daikto, kurio jam nereikia.",
      "Galiausiai prisiminkite: dovana neturi įrodyti, kad sugebate nustebinti žmogų, kuris daug matė. Ji turi suteikti jam vieną malonią, lengvai priimamą akimirką.",
    ],
  },
];

export const SCHEDULED_ARTICLES_2026: ArticleRecord[] = briefs.map((brief) => ({
  id: brief.id,
  siteId: "dovanos123",
  locale: "lt-LT",
  slug: brief.slug,
  title: brief.title,
  excerpt: brief.excerpt,
  category: brief.category,
  publishAt: `${brief.day}T07:30:00+03:00`,
  publicationState: "scheduled",
  readingMinutes: Math.max(3, Math.round(brief.body.join(" ").split(/\s+/).length / 180)),
  relatedIds: brief.relatedIds,
  authorIds: ["dovanos123-redakcija"],
  sourceIds: brief.productRecommendation ? ["source-memorycasting"] : [],
  productRecommendation: brief.productRecommendation ?? false,
  featuredImage: {
    src: `/images/articles/${brief.image}`,
    alt: brief.imageAlt,
    width: 1536,
    height: 1024,
    credit: "AI sugeneruota redakcinė iliustracija; ne konkrečios prekės fotografija",
  },
  body: brief.body,
}));
