-- Dedicated PhoneBridger additive migration. No existing account/order/native data is replaced.
CREATE TABLE IF NOT EXISTS account_profiles (user_id TEXT PRIMARY KEY,display_name TEXT NOT NULL DEFAULT '',notifications INTEGER NOT NULL DEFAULT 0,setup TEXT NOT NULL DEFAULT '[]');
CREATE TABLE IF NOT EXISTS support_tickets (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,order_id TEXT,subject TEXT NOT NULL,message TEXT NOT NULL,diagnostics TEXT,status TEXT NOT NULL DEFAULT 'open',created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS support_owner ON support_tickets(user_id,created_at);
CREATE TABLE IF NOT EXISTS support_replies (id TEXT PRIMARY KEY,ticket_id TEXT NOT NULL REFERENCES support_tickets(id),sender TEXT NOT NULL CHECK(sender IN ('customer','support')),message TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS support_reply_ticket ON support_replies(ticket_id,created_at);
CREATE TABLE IF NOT EXISTS creator_applications (user_id TEXT PRIMARY KEY,channels TEXT NOT NULL,audience TEXT NOT NULL,message TEXT NOT NULL,terms_version TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('pending','approved','rejected','suspended')),created_at INTEGER NOT NULL,reviewed_at INTEGER);
CREATE TABLE IF NOT EXISTS creator_partners (id TEXT PRIMARY KEY,user_id TEXT NOT NULL UNIQUE,code TEXT NOT NULL UNIQUE,status TEXT NOT NULL CHECK(status IN ('approved','suspended')),accepted_terms TEXT,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS affiliate_terms (version TEXT PRIMARY KEY,definition TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS immutable_terms_update BEFORE UPDATE ON affiliate_terms BEGIN SELECT RAISE(ABORT,'Terms are immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_terms_delete BEFORE DELETE ON affiliate_terms BEGIN SELECT RAISE(ABORT,'Terms are immutable'); END;
CREATE TABLE IF NOT EXISTS affiliate_links (id TEXT PRIMARY KEY,partner_id TEXT NOT NULL,tag TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS affiliate_link_owner ON affiliate_links(partner_id,created_at);
CREATE TABLE IF NOT EXISTS affiliate_clicks (id TEXT PRIMARY KEY,link_id TEXT NOT NULL,visitor_digest TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS affiliate_click_time ON affiliate_clicks(link_id,created_at);
CREATE TABLE IF NOT EXISTS affiliate_order_snapshots (order_id TEXT PRIMARY KEY,partner_id TEXT NOT NULL,link_id TEXT,terms_version TEXT NOT NULL,currency TEXT NOT NULL,basis INTEGER NOT NULL,rate_bps INTEGER NOT NULL,discount_minor INTEGER NOT NULL,created_at INTEGER NOT NULL);
CREATE TRIGGER IF NOT EXISTS immutable_attribution_update BEFORE UPDATE ON affiliate_order_snapshots BEGIN SELECT RAISE(ABORT,'Attribution is immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_attribution_delete BEFORE DELETE ON affiliate_order_snapshots BEGIN SELECT RAISE(ABORT,'Attribution is immutable'); END;
CREATE TABLE IF NOT EXISTS affiliate_commissions (id TEXT PRIMARY KEY,order_id TEXT NOT NULL UNIQUE,partner_id TEXT NOT NULL,buyer_id TEXT NOT NULL UNIQUE,currency TEXT NOT NULL,basis INTEGER NOT NULL,rate_bps INTEGER NOT NULL,amount INTEGER NOT NULL,terms_version TEXT NOT NULL,paid_at INTEGER NOT NULL,holders INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS affiliate_commission_owner ON affiliate_commissions(partner_id,paid_at);
CREATE TRIGGER IF NOT EXISTS immutable_commission_update BEFORE UPDATE ON affiliate_commissions BEGIN SELECT RAISE(ABORT,'Commission is immutable'); END;
CREATE TRIGGER IF NOT EXISTS immutable_commission_delete BEFORE DELETE ON affiliate_commissions BEGIN SELECT RAISE(ABORT,'Commission is immutable'); END;
CREATE TABLE IF NOT EXISTS affiliate_ledger (seq INTEGER PRIMARY KEY AUTOINCREMENT,id TEXT NOT NULL UNIQUE,commission_id TEXT NOT NULL REFERENCES affiliate_commissions(id),bucket TEXT NOT NULL CHECK(bucket IN ('Pending','Available','Reserved','Paid','Reversed','Review')),amount INTEGER NOT NULL,reason TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS affiliate_ledger_commission ON affiliate_ledger(commission_id,bucket);
CREATE TRIGGER IF NOT EXISTS immutable_ledger_update BEFORE UPDATE ON affiliate_ledger BEGIN SELECT RAISE(ABORT,'Ledger is append-only'); END;
CREATE TRIGGER IF NOT EXISTS immutable_ledger_delete BEFORE DELETE ON affiliate_ledger BEGIN SELECT RAISE(ABORT,'Ledger is append-only'); END;
CREATE TRIGGER IF NOT EXISTS ledger_nonnegative BEFORE INSERT ON affiliate_ledger WHEN NEW.amount + COALESCE((SELECT SUM(amount) FROM affiliate_ledger WHERE commission_id=NEW.commission_id AND bucket=NEW.bucket),0)<0 BEGIN SELECT RAISE(ABORT,'Insufficient ledger balance'); END;
CREATE TABLE IF NOT EXISTS affiliate_payouts (id TEXT PRIMARY KEY,partner_id TEXT NOT NULL,currency TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('reserved','paid','failed','review')),created_at INTEGER NOT NULL,completed_at INTEGER,provider_reference TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS affiliate_payout_items (payout_id TEXT NOT NULL,commission_id TEXT NOT NULL,amount INTEGER NOT NULL,PRIMARY KEY(payout_id,commission_id));
CREATE TABLE IF NOT EXISTS creator_content (id TEXT PRIMARY KEY,partner_id TEXT NOT NULL,url TEXT NOT NULL,label TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS creator_operations (id TEXT PRIMARY KEY,action TEXT NOT NULL,subject_id TEXT NOT NULL,created_at INTEGER NOT NULL);
